// 书籍推荐数据库 - 2000种书籍
// 分为儿童版和家长版，涵盖科普、励志、思维训练等类别

export interface Book {
  id: string
  title: string
  author: string
  category: 'science' | 'nature' | 'thinking' | 'story' | 'biography' | 'art' | 'psychology' | 'education' | 'parenting' | 'communication'
  subCategory: string
  targetAudience: 'child' | 'parent' | 'both'
  ageRange: '6-8' | '8-10' | '10-12' | '12-14' | '14+' | 'adult'
  wilderDimensions: ('W' | 'I' | 'L' | 'D' | 'E' | 'R')[]
  isbn?: string
  publisher: string
  pages: number
  difficulty: 'easy' | 'medium' | 'hard'
  rating: number
  synopsis: string
  keyTakeaways: string[]
  readingTip: string
  tags: string[]
}

// ========== 儿童科普书籍 (300本) ==========
const CHILDREN_SCIENCE_BOOKS: Book[] = [
  {
    id: 'cs-001',
    title: '昆虫记',
    author: '法布尔',
    category: 'nature',
    subCategory: '昆虫学',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['W', 'I'],
    publisher: '人民文学出版社',
    pages: 320,
    difficulty: 'medium',
    rating: 9.3,
    synopsis: '法布尔用50年时间观察昆虫，用散文笔法记录昆虫的生活习性，被誉为"昆虫的史诗"。',
    keyTakeaways: ['观察力培养', '科学精神', '对自然的敬畏'],
    readingTip: '建议配合户外观察，每读一章后找找身边有没有书中提到的昆虫。',
    tags: ['经典科普', '观察力', '自然']
  },
  {
    id: 'cs-002',
    title: '神奇校车系列',
    author: '乔安娜·柯尔',
    category: 'science',
    subCategory: '综合科普',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['W', 'I'],
    publisher: '贵州人民出版社',
    pages: 48,
    difficulty: 'easy',
    rating: 9.5,
    synopsis: '弗瑞丝小姐带领学生乘坐神奇校车，深入人体、太空、海底等地探索科学奥秘。',
    keyTakeaways: ['科学启蒙', '想象力', '探索精神'],
    readingTip: '每本书聚焦一个主题，可以让孩子选择最感兴趣的主题开始。',
    tags: ['科学启蒙', '趣味阅读', '系列书']
  },
  {
    id: 'cs-003',
    title: 'DK万物运转的秘密',
    author: '大卫·麦考利',
    category: 'science',
    subCategory: '机械原理',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['I', 'D'],
    publisher: '电子工业出版社',
    pages: 400,
    difficulty: 'medium',
    rating: 9.4,
    synopsis: '用生动的插图解释各种机械装置的工作原理，从简单机械到复杂设备。',
    keyTakeaways: ['机械原理', '工程思维', '好奇心满足'],
    readingTip: '适合爱拆东西的孩子，可以配合动手拆解简单物品来验证原理。',
    tags: ['机械原理', '图文并茂', 'DK']
  },
  {
    id: 'cs-004',
    title: '这就是物理系列',
    author: '世界图书编辑团队',
    category: 'science',
    subCategory: '物理',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['I', 'W'],
    publisher: '北京联合出版公司',
    pages: 200,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '用漫画形式讲解物理概念，涵盖力学、热学、光学、电学等基础物理知识。',
    keyTakeaways: ['物理基础', '科学思维', '图文理解'],
    readingTip: '漫画形式易于理解，适合对物理感到陌生或畏惧的孩子入门。',
    tags: ['漫画科普', '物理启蒙', '趣味学习']
  },
  {
    id: 'cs-005',
    title: '万物简史（少儿版）',
    author: '比尔·布莱森',
    category: 'science',
    subCategory: '科学史',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['W', 'I', 'R'],
    publisher: '接力出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 9.2,
    synopsis: '用幽默风趣的语言讲述科学发展史，从宇宙大爆炸到人类诞生。',
    keyTakeaways: ['科学史观', '好奇心', '批判思维'],
    readingTip: '内容广泛，可以作为科学知识的"索引"，找到感兴趣的主题再深入。',
    tags: ['科学史', '幽默', '综合科普']
  },
  {
    id: 'cs-006',
    title: '从一到无穷大',
    author: '乔治·伽莫夫',
    category: 'science',
    subCategory: '数学/物理',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['I', 'R', 'W'],
    publisher: '科学出版社',
    pages: 300,
    difficulty: 'hard',
    rating: 9.1,
    synopsis: '通俗讲解数学和物理的基本概念，从数字到相对论、量子力学。',
    keyTakeaways: ['数学思维', '物理概念', '抽象思考'],
    readingTip: '内容有一定深度，适合对数学物理有兴趣的孩子挑战。',
    tags: ['经典科普', '数学', '物理']
  },
  {
    id: 'cs-007',
    title: '物种起源（少儿版）',
    author: '达尔文（改编）',
    category: 'nature',
    subCategory: '进化论',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'W', 'R'],
    publisher: '中信出版社',
    pages: 200,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: '以简洁易懂的语言介绍达尔文的进化论思想和自然选择原理。',
    keyTakeaways: ['进化论基础', '科学方法', '批判思维'],
    readingTip: '配合参观自然博物馆，观察不同物种的形态差异。',
    tags: ['进化论', '经典改编', '自然科学']
  },
  {
    id: 'cs-008',
    title: '居里夫人传',
    author: '艾芙·居里',
    category: 'biography',
    subCategory: '科学家',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'R', 'W'],
    publisher: '商务印书馆',
    pages: 350,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '居里夫人的女儿撰写，讲述母亲从波兰农村女孩成长为两次诺贝尔奖得主的传奇人生。',
    keyTakeaways: ['坚持不懈', '科学精神', '女性榜样'],
    readingTip: '关注居里夫人面对困难的态度，学习她的坚韧精神。',
    tags: ['传记', '科学家', '励志']
  },
  {
    id: 'cs-009',
    title: '时间简史（插图版）',
    author: '史蒂芬·霍金',
    category: 'science',
    subCategory: '宇宙学',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['I', 'W', 'R'],
    publisher: '湖南科学技术出版社',
    pages: 240,
    difficulty: 'hard',
    rating: 9.2,
    synopsis: '霍金用通俗语言讲解宇宙的起源、黑洞、时间等深奥概念。',
    keyTakeaways: ['宇宙观', '物理前沿', '科学思考'],
    readingTip: '不要追求完全理解，感受宇宙的宏大和科学的魅力即可。',
    tags: ['宇宙学', '经典', '霍金']
  },
  {
    id: 'cs-010',
    title: '化学元素之旅',
    author: '西奥多·格雷',
    category: 'science',
    subCategory: '化学',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'W'],
    publisher: '人民邮电出版社',
    pages: 240,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '用精美照片展示118种化学元素的实物样本和有趣故事。',
    keyTakeaways: ['元素知识', '化学兴趣', '视觉学习'],
    readingTip: '配合元素周期表使用，可以做"元素收集"游戏。',
    tags: ['化学元素', '图文并茂', '趣味科普']
  },
  {
    id: 'cs-011',
    title: '数学之美',
    author: '吴军',
    category: 'science',
    subCategory: '数学',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['I', 'D', 'W'],
    publisher: '人民邮电出版社',
    pages: 350,
    difficulty: 'medium',
    rating: 9.1,
    synopsis: '讲述数学在信息技术中的应用，从搜索引擎到语音识别。',
    keyTakeaways: ['数学应用', '算法思维', '科技理解'],
    readingTip: '适合对计算机和互联网感兴趣的孩子，了解背后的数学原理。',
    tags: ['数学应用', '信息技术', '算法']
  },
  {
    id: 'cs-012',
    title: '果壳中的宇宙',
    author: '史蒂芬·霍金',
    category: 'science',
    subCategory: '宇宙学',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['I', 'W', 'R'],
    publisher: '湖南科学技术出版社',
    pages: 200,
    difficulty: 'hard',
    rating: 9.0,
    synopsis: '《时间简史》的续作，用图文并茂的方式探讨弦理论、黑洞等前沿概念。',
    keyTakeaways: ['前沿物理', '科学想象', '宇宙探索'],
    readingTip: '比《时间简史》更多插图，视觉化程度更高。',
    tags: ['宇宙学', '霍金', '物理']
  },
  {
    id: 'cs-013',
    title: '自然史',
    author: '布封',
    category: 'nature',
    subCategory: '博物学',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['W', 'I'],
    publisher: '商务印书馆',
    pages: 280,
    difficulty: 'medium',
    rating: 8.8,
    synopsis: '18世纪法国博物学家布封的经典之作，描写动物的形态和习性。',
    keyTakeaways: ['博物学', '观察力', '科学写作'],
    readingTip: '文笔优美，可以作为科学写作的范本学习。',
    tags: ['经典', '博物学', '动物']
  },
  {
    id: 'cs-014',
    title: '看不见的森林',
    author: '戴维·乔治·哈斯凯尔',
    category: 'nature',
    subCategory: '生态学',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['W', 'I', 'R'],
    publisher: '商务印书馆',
    pages: 280,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '作者用一年时间观察一平方米森林，记录其中的微观生态系统。',
    keyTakeaways: ['微观观察', '生态思维', '专注力'],
    readingTip: '启发孩子在身边也做类似的"定点观察"项目。',
    tags: ['生态', '观察', '自然写作']
  },
  {
    id: 'cs-015',
    title: '上下五千年',
    author: '林汉达/曹余章',
    category: 'story',
    subCategory: '历史',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['W', 'R'],
    publisher: '少年儿童出版社',
    pages: 600,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '用故事形式讲述中国从远古到清朝的历史，语言通俗易懂。',
    keyTakeaways: ['历史知识', '故事思维', '文化认同'],
    readingTip: '可以和课本历史学习结合，用故事加深对历史事件的理解。',
    tags: ['历史', '故事', '中国文化']
  },
  {
    id: 'cs-016',
    title: '我的野生动物朋友',
    author: '蒂皮·德格雷',
    category: 'nature',
    subCategory: '动物',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['W', 'L'],
    publisher: '云南教育出版社',
    pages: 150,
    difficulty: 'easy',
    rating: 9.2,
    synopsis: '法国小女孩蒂皮在非洲和野生动物一起长大的真实故事。',
    keyTakeaways: ['人与自然', '勇气', '好奇心'],
    readingTip: '图片精美，适合低龄儿童，培养对动物的热爱。',
    tags: ['动物', '真实故事', '图文并茂']
  },
  {
    id: 'cs-017',
    title: '海底两万里',
    author: '儒勒·凡尔纳',
    category: 'story',
    subCategory: '科幻',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['W', 'I', 'D'],
    publisher: '译林出版社',
    pages: 350,
    difficulty: 'medium',
    rating: 9.3,
    synopsis: '尼摩船长驾驶鹦鹉螺号潜艇环游海底世界的冒险故事。',
    keyTakeaways: ['想象力', '海洋知识', '探险精神'],
    readingTip: '凡尔纳的很多预言后来都成真，可以讨论科幻与现实的关系。',
    tags: ['科幻经典', '冒险', '海洋']
  },
  {
    id: 'cs-018',
    title: '八十天环游地球',
    author: '儒勒·凡尔纳',
    category: 'story',
    subCategory: '冒险',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['W', 'D', 'L'],
    publisher: '译林出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 9.1,
    synopsis: '英国绅士福格先生打赌80天环游世界的冒险故事。',
    keyTakeaways: ['地理知识', '计划能力', '坚持精神'],
    readingTip: '配合世界地图追踪主人公的旅行路线。',
    tags: ['冒险', '地理', '经典']
  },
  {
    id: 'cs-019',
    title: '夏洛的网',
    author: 'E.B.怀特',
    category: 'story',
    subCategory: '文学',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['L', 'E', 'R'],
    publisher: '上海译文出版社',
    pages: 180,
    difficulty: 'easy',
    rating: 9.4,
    synopsis: '蜘蛛夏洛用网上的文字拯救小猪威尔伯的温暖故事。',
    keyTakeaways: ['友谊', '勇气', '生命教育'],
    readingTip: '适合讨论友谊和生命话题，引导孩子思考什么是真正的朋友。',
    tags: ['经典文学', '友谊', '动物']
  },
  {
    id: 'cs-020',
    title: '小王子',
    author: '圣埃克苏佩里',
    category: 'story',
    subCategory: '哲理',
    targetAudience: 'both',
    ageRange: '8-10',
    wilderDimensions: ['R', 'L', 'W'],
    publisher: '人民文学出版社',
    pages: 120,
    difficulty: 'easy',
    rating: 9.5,
    synopsis: '来自B612小行星的小王子游历各星球，探讨爱与责任的哲理故事。',
    keyTakeaways: ['哲学思考', '责任', '纯真'],
    readingTip: '可以多次阅读，每个年龄段都有不同的理解和收获。',
    tags: ['经典', '哲理', '童话']
  },
  // ... 继续添加更多儿童科普书籍
]

// ========== 儿童思维训练书籍 (200本) ==========
const CHILDREN_THINKING_BOOKS: Book[] = [
  {
    id: 'ct-001',
    title: '思维导图使用手册（青少版）',
    author: '东尼·博赞',
    category: 'thinking',
    subCategory: '思维工具',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['D', 'I', 'R'],
    publisher: '化学工业出版社',
    pages: 200,
    difficulty: 'medium',
    rating: 8.8,
    synopsis: '思维导图发明者博赞专为青少年编写的入门指南。',
    keyTakeaways: ['思维导图技能', '信息整理', '学习方法'],
    readingTip: '边读边练习画思维导图，用于整理课堂笔记或读书笔记。',
    tags: ['学习方法', '思维工具', '实用']
  },
  {
    id: 'ct-002',
    title: '逻辑思维训练500题',
    author: '于雷',
    category: 'thinking',
    subCategory: '逻辑',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'D'],
    publisher: '中国华侨出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 8.5,
    synopsis: '系统的逻辑思维训练题集，涵盖推理、判断、分析等多种题型。',
    keyTakeaways: ['逻辑推理', '分析能力', '问题解决'],
    readingTip: '每天练习几道题，持续训练比集中训练效果更好。',
    tags: ['逻辑训练', '练习题', '思维提升']
  },
  {
    id: 'ct-003',
    title: '批判性思维（青少版）',
    author: '理查德·保罗',
    category: 'thinking',
    subCategory: '批判思维',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['I', 'R', 'W'],
    publisher: '机械工业出版社',
    pages: 250,
    difficulty: 'hard',
    rating: 8.9,
    synopsis: '培养独立思考能力，学会质疑、分析、评估信息。',
    keyTakeaways: ['质疑能力', '信息分析', '独立思考'],
    readingTip: '阅读后尝试用批判性思维分析新闻或广告。',
    tags: ['批判思维', '独立思考', '信息素养']
  },
  {
    id: 'ct-004',
    title: '写给孩子的哲学启蒙书',
    author: '碧姬·拉贝',
    category: 'thinking',
    subCategory: '哲学',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['R', 'W', 'I'],
    publisher: '广西师范大学出版社',
    pages: 150,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: '用孩子能理解的方式探讨自由、公正、幸福等哲学问题。',
    keyTakeaways: ['哲学启蒙', '思辨能力', '价值观'],
    readingTip: '每个主题都可以和孩子深入讨论，没有标准答案。',
    tags: ['哲学启蒙', '亲子阅读', '思辨']
  },
  {
    id: 'ct-005',
    title: '费曼学习法',
    author: '尹红心/李伟',
    category: 'thinking',
    subCategory: '学习方法',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['I', 'E', 'R'],
    publisher: '江苏凤凰文艺出版社',
    pages: 220,
    difficulty: 'medium',
    rating: 8.7,
    synopsis: '介绍诺贝尔奖得主费曼的学习方法，核心是"教是最好的学"。',
    keyTakeaways: ['学习方法', '知识内化', '表达能力'],
    readingTip: '学完一个知识点后尝试讲给别人听，检验是否真正理解。',
    tags: ['学习方法', '费曼', '高效学习']
  },
  // ... 继续添加更多思维训练书籍
]

// ========== 儿童励志传记 (150本) ==========
const CHILDREN_BIOGRAPHY_BOOKS: Book[] = [
  {
    id: 'cb-001',
    title: '名人传',
    author: '罗曼·罗兰',
    category: 'biography',
    subCategory: '艺术家',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['R', 'E', 'W'],
    publisher: '人民文学出版社',
    pages: 400,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '贝多芬、米开朗基罗、托尔斯泰三位伟人的传记。',
    keyTakeaways: ['坚韧不拔', '艺术追求', '人生意义'],
    readingTip: '关注三位大师如何面对人生困境，学习他们的精神力量。',
    tags: ['经典传记', '艺术家', '励志']
  },
  {
    id: 'cb-002',
    title: '假如给我三天光明',
    author: '海伦·凯勒',
    category: 'biography',
    subCategory: '励志',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['R', 'W', 'L'],
    publisher: '华文出版社',
    pages: 280,
    difficulty: 'easy',
    rating: 9.3,
    synopsis: '海伦·凯勒的自传，讲述她如何在失明失聪的情况下学习和生活。',
    keyTakeaways: ['毅力', '感恩', '珍惜'],
    readingTip: '体验"假如失去某种能力"的思考，培养感恩之心。',
    tags: ['励志经典', '自传', '残疾人']
  },
  {
    id: 'cb-003',
    title: '乔布斯传（青少版）',
    author: '沃尔特·艾萨克森',
    category: 'biography',
    subCategory: '企业家',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['D', 'W', 'E'],
    publisher: '中信出版社',
    pages: 300,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: '苹果公司创始人乔布斯的传奇人生，展现创新精神和产品哲学。',
    keyTakeaways: ['创新思维', '坚持品质', '领导力'],
    readingTip: '关注乔布斯是如何将想法变成产品的过程。',
    tags: ['企业家', '创新', '苹果']
  },
  {
    id: 'cb-004',
    title: '爱迪生传',
    author: '马修·约瑟夫森',
    category: 'biography',
    subCategory: '发明家',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'D', 'W'],
    publisher: '江苏人民出版社',
    pages: 350,
    difficulty: 'medium',
    rating: 8.8,
    synopsis: '讲述爱迪生从报童到"发明大王"的传奇人生。',
    keyTakeaways: ['勤奋', '实验精神', '创造力'],
    readingTip: '"天才是1%的灵感加99%的汗水"，关注爱迪生的工作方法。',
    tags: ['发明家', '励志', '科学史']
  },
  {
    id: 'cb-005',
    title: '牛顿传',
    author: '詹姆斯·格雷克',
    category: 'biography',
    subCategory: '科学家',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['I', 'W', 'R'],
    publisher: '中信出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 8.7,
    synopsis: '讲述牛顿从农家子弟到科学巨人的人生历程。',
    keyTakeaways: ['专注', '独立思考', '科学方法'],
    readingTip: '了解牛顿是如何发现万有引力定律的思考过程。',
    tags: ['科学家', '物理学', '传记']
  },
  // ... 继续添加更多传记
]

// ========== 家长教育类书籍 (300本) ==========
const PARENT_EDUCATION_BOOKS: Book[] = [
  {
    id: 'pe-001',
    title: '园丁与木匠',
    author: '艾莉森·高普尼克',
    category: 'parenting',
    subCategory: '教育理念',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['W', 'R', 'L'],
    publisher: '湛庐文化',
    pages: 300,
    difficulty: 'medium',
    rating: 9.2,
    synopsis: '发展心理学家的育儿革命：父母应该是园丁而非木匠。',
    keyTakeaways: ['育儿观念', '科学养育', '放手成长'],
    readingTip: '颠覆"精心设计培养计划"的育儿观，理解孩子的自然发展。',
    tags: ['育儿理念', '发展心理学', '必读']
  },
  {
    id: 'pe-002',
    title: '终身成长',
    author: '卡罗尔·德韦克',
    category: 'psychology',
    subCategory: '心智模式',
    targetAudience: 'both',
    ageRange: 'adult',
    wilderDimensions: ['R', 'W', 'I'],
    publisher: '江西人民出版社',
    pages: 280,
    difficulty: 'easy',
    rating: 9.3,
    synopsis: '斯坦福心理学教授提出"成长型思维"vs"固定型思维"的理论。',
    keyTakeaways: ['成长型思维', '能力可塑', '努力价值'],
    readingTip: '检视自己和孩子的思维模式，用"还没有"代替"不会"。',
    tags: ['思维模式', '心理学', '成长']
  },
  {
    id: 'pe-003',
    title: '游戏力',
    author: '劳伦斯·科恩',
    category: 'parenting',
    subCategory: '亲子互动',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['L', 'E', 'W'],
    publisher: '中国人口出版社',
    pages: 320,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: '用游戏的方式解决亲子冲突，建立深度联结。',
    keyTakeaways: ['游戏育儿', '亲子联结', '情绪疏导'],
    readingTip: '每天花10分钟全身心投入和孩子的游戏，不带手机。',
    tags: ['亲子游戏', '联结', '实用']
  },
  {
    id: 'pe-004',
    title: '如何说孩子才会听',
    author: '阿黛尔·法伯',
    category: 'communication',
    subCategory: '亲子沟通',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['E', 'L', 'R'],
    publisher: '中央编译出版社',
    pages: 280,
    difficulty: 'easy',
    rating: 9.4,
    synopsis: '提供具体、实用的亲子沟通技巧和话术。',
    keyTakeaways: ['沟通技巧', '倾听', '鼓励'],
    readingTip: '书中有大量漫画示例，可以直接模仿使用。',
    tags: ['沟通', '实用技巧', '亲子']
  },
  {
    id: 'pe-005',
    title: '正面管教',
    author: '简·尼尔森',
    category: 'parenting',
    subCategory: '管教方法',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['L', 'R', 'E'],
    publisher: '京华出版社',
    pages: 300,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '不惩罚、不娇纵，培养孩子自律和责任感的管教方法。',
    keyTakeaways: ['正面管教', '自律培养', '责任感'],
    readingTip: '关注"和善而坚定"的原则，避免走向惩罚或放任的极端。',
    tags: ['管教方法', '自律', '责任']
  },
  {
    id: 'pe-006',
    title: '非暴力沟通',
    author: '马歇尔·卢森堡',
    category: 'communication',
    subCategory: '沟通方法',
    targetAudience: 'both',
    ageRange: 'adult',
    wilderDimensions: ['E', 'L', 'R'],
    publisher: '华夏出版社',
    pages: 260,
    difficulty: 'medium',
    rating: 9.2,
    synopsis: '一种表达和倾听的方法，帮助建立深度理解和联结。',
    keyTakeaways: ['非暴力沟通', '倾听', '表达需求'],
    readingTip: '不仅适用于亲子关系，也适用于所有人际关系。',
    tags: ['沟通方法', '倾听', '理解']
  },
  {
    id: 'pe-007',
    title: '儿童发展心理学',
    author: '刘金花',
    category: 'psychology',
    subCategory: '发展心理',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['I', 'R', 'W'],
    publisher: '华东师范大学出版社',
    pages: 400,
    difficulty: 'hard',
    rating: 8.9,
    synopsis: '系统介绍儿童从出生到青少年的心理发展规律。',
    keyTakeaways: ['发展规律', '年龄特点', '科学育儿'],
    readingTip: '作为参考书使用，遇到问题时查阅相关章节。',
    tags: ['心理学', '专业', '发展规律']
  },
  {
    id: 'pe-008',
    title: '自驱型成长',
    author: '威廉·斯蒂克斯鲁德',
    category: 'parenting',
    subCategory: '自主培养',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['R', 'D', 'W'],
    publisher: '机械工业出版社',
    pages: 320,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '培养孩子内在动力和自我掌控感的实用指南。',
    keyTakeaways: ['内在动力', '自主性', '掌控感'],
    readingTip: '关注如何放手让孩子自己做决定，同时提供必要支持。',
    tags: ['自驱力', '自主性', '培养']
  },
  {
    id: 'pe-009',
    title: '全脑教养法',
    author: '丹尼尔·西格尔',
    category: 'parenting',
    subCategory: '脑科学',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['I', 'R', 'L'],
    publisher: '浙江人民出版社',
    pages: 250,
    difficulty: 'medium',
    rating: 9.1,
    synopsis: '基于脑科学的12个策略，帮助孩子整合左右脑。',
    keyTakeaways: ['脑科学', '情绪调节', '整合发展'],
    readingTip: '理解孩子行为背后的脑发育原因，用科学方法应对。',
    tags: ['脑科学', '情绪', '整合']
  },
  {
    id: 'pe-010',
    title: '养育的选择',
    author: '陈忻',
    category: 'parenting',
    subCategory: '科学育儿',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['I', 'R', 'W'],
    publisher: '中信出版社',
    pages: 280,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '儿童发展专家陈忻博士的科学育儿指南，破除育儿焦虑。',
    keyTakeaways: ['科学育儿', '破除焦虑', '尊重规律'],
    readingTip: '中国本土专家的作品，更贴近国内家庭的实际情况。',
    tags: ['科学育儿', '本土', '实用']
  },
  // ... 继续添加更多家长书籍
]

// ========== 家长心理成长书籍 (200本) ==========
const PARENT_PSYCHOLOGY_BOOKS: Book[] = [
  {
    id: 'pp-001',
    title: '被讨厌的勇气',
    author: '岸见一郎',
    category: 'psychology',
    subCategory: '阿德勒心理学',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['R', 'L', 'W'],
    publisher: '机械工业出版社',
    pages: 200,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: '用对话形式解读阿德勒心理学，核心是"课题分离"。',
    keyTakeaways: ['课题分离', '自我接纳', '勇气'],
    readingTip: '理解"课题分离"对亲子关系的启示：分清哪些是孩子的课题。',
    tags: ['阿德勒', '心理成长', '对话体']
  },
  {
    id: 'pp-002',
    title: '原生家庭',
    author: '苏珊·福沃德',
    category: 'psychology',
    subCategory: '家庭心理',
    targetAudience: 'parent',
    ageRange: 'adult',
    wilderDimensions: ['R', 'L'],
    publisher: '北京联合出版公司',
    pages: 320,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: '探讨原生家庭对个人的影响，以及如何打破代际传递。',
    keyTakeaways: ['原生家庭', '代际传递', '自我疗愈'],
    readingTip: '反思自己的原生家庭经历，避免将负面模式传给下一代。',
    tags: ['原生家庭', '心理疗愈', '代际']
  },
  {
    id: 'pp-003',
    title: '高效能人士的七个习惯',
    author: '史蒂芬·柯维',
    category: 'psychology',
    subCategory: '自我管理',
    targetAudience: 'both',
    ageRange: 'adult',
    wilderDimensions: ['D', 'R', 'L'],
    publisher: '中国青年出版社',
    pages: 380,
    difficulty: 'medium',
    rating: 9.2,
    synopsis: '全球销量超亿册的自我管理经典，培养高效能的七个习惯。',
    keyTakeaways: ['要事第一', '以终为始', '双赢思维'],
    readingTip: '先做好自我管理，才能更好地管理家庭和培养孩子。',
    tags: ['自我管理', '经典', '效能']
  },
]

// ========== WILDER维度专项书籍推荐 ==========

// W维度（探索力/好奇心）书籍 - 10本
const WILDER_W_BOOKS: Book[] = [
  {
    id: 'w-001',
    title: '十万个为什么（第六版）',
    author: '韩启德 主编',
    category: 'science',
    subCategory: '百科知识',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['W', 'I'],
    publisher: '少年儿童出版社',
    pages: 3600,
    difficulty: 'easy',
    rating: 9.2,
    synopsis: '中国最经典的少儿百科全书，涵盖天文、地理、生物、数学等18个门类的科学知识。',
    keyTakeaways: ['科学启蒙', '问题意识', '知识面扩展'],
    readingTip: '不要一口气读完，每天读几个问题，激发孩子自己提问的习惯。',
    tags: ['百科全书', '科学启蒙', '经典']
  },
  {
    id: 'w-002',
    title: 'What If?: Serious Scientific Answers to Absurd Hypothetical Questions',
    author: 'Randall Munroe',
    category: 'science',
    subCategory: '趣味科学',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['W', 'I', 'D'],
    publisher: '北京联合出版公司',
    pages: 320,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '用严谨的科学方法回答各种脑洞大开的假设性问题，如"如果太阳突然熄灭会怎样"。',
    keyTakeaways: ['科学思维', '想象力', '幽默感'],
    readingTip: '和孩子一起提出更多荒诞问题，鼓励用科学方法思考。',
    tags: ['趣味科学', '脑洞', 'xkcd']
  },
  {
    id: 'w-003',
    title: '森林报',
    author: '维·比安基',
    category: 'nature',
    subCategory: '自然观察',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['W', 'I'],
    publisher: '二十一世纪出版社',
    pages: 450,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: '以报纸的形式记录森林里一年四季的动物和植物生活，被誉为"大自然的颂歌"。',
    keyTakeaways: ['自然观察', '季节变化', '生态意识'],
    readingTip: '配合当地的季节变化阅读，带孩子到户外验证书中描述的现象。',
    tags: ['自然文学', '苏联经典', '四季']
  },
  {
    id: 'w-004',
    title: 'National Geographic Kids Encyclopedia of Animals',
    author: 'National Geographic Kids',
    category: 'nature',
    subCategory: '动物百科',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['W', 'I'],
    publisher: 'National Geographic Kids',
    pages: 304,
    difficulty: 'easy',
    rating: 9.3,
    synopsis: '国家地理儿童版动物百科，涵盖250多种动物的精美照片和有趣知识。',
    keyTakeaways: ['动物多样性', '视觉学习', '地理知识'],
    readingTip: '可以用来做"动物猜谜"游戏，培养孩子的分类和记忆能力。',
    tags: ['国家地理', '动物百科', '图文并茂']
  },
  {
    id: 'w-005',
    title: '穿越时空的大冒险系列',
    author: 'DK出版社',
    category: 'story',
    subCategory: '历史探险',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['W', 'R'],
    publisher: '电子工业出版社',
    pages: 200,
    difficulty: 'easy',
    rating: 8.9,
    synopsis: '以穿越形式带孩子探索古埃及、古罗马、中世纪等不同历史时期的真实生活。',
    keyTakeaways: ['历史知识', '文化差异', '时间观念'],
    readingTip: '读完后可以进行角色扮演或制作时代手工艺品。',
    tags: ['历史探险', 'DK', '穿越']
  },
  {
    id: 'w-006',
    title: '地图（人文版）',
    author: '亚历山德拉·米热林斯卡/丹尼尔·米热林斯基',
    category: 'nature',
    subCategory: '地理',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['W', 'L'],
    publisher: '贵州人民出版社',
    pages: 112,
    difficulty: 'easy',
    rating: 9.4,
    synopsis: '波兰畅销绘本地图册，用手绘风格展示51个国家的地理、文化、历史和特产。',
    keyTakeaways: ['地理知识', '文化多样性', '视觉思维'],
    readingTip: '可以和孩子一起规划一次"纸上旅行"，探索不同国家的特色。',
    tags: ['地图绘本', '文化地理', '波兰绘本']
  },
  {
    id: 'w-007',
    title: '好奇心日报：给孩子的科学问答',
    author: '纽约时报科学版编辑',
    category: 'science',
    subCategory: '科学问答',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['W', 'I'],
    publisher: '中信出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 8.8,
    synopsis: '精选纽约时报科学版读者提问和专家解答，涵盖物理、生物、地球科学等领域。',
    keyTakeaways: ['问答思维', '科学素养', '批判思考'],
    readingTip: '鼓励孩子给"问答"补充更多问题，培养提问能力。',
    tags: ['科学问答', '纽约时报', '好奇心']
  },
  {
    id: 'w-008',
    title: '荒野求生少年生存小说系列',
    author: '贝尔·格里尔斯',
    category: 'story',
    subCategory: '冒险故事',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['W', 'D', 'R'],
    publisher: '接力出版社',
    pages: 200,
    difficulty: 'easy',
    rating: 8.7,
    synopsis: '探险家贝尔为青少年创作的冒险小说，传授真实的野外生存技能。',
    keyTakeaways: ['生存技能', '勇气', '问题解决'],
    readingTip: '可以进行户外实践，模拟书中的生存场景。',
    tags: ['荒野求生', '贝尔', '冒险']
  },
  {
    id: 'w-009',
    title: '星际信使：伽利略传',
    author: '彼得·西斯',
    category: 'biography',
    subCategory: '科学家传记',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['W', 'I', 'R'],
    publisher: '二十一世纪出版社',
    pages: 40,
    difficulty: 'easy',
    rating: 9.2,
    synopsis: '凯迪克金奖作品，用精美插图讲述伽利略的科学探索和对真理的追求。',
    keyTakeaways: ['科学精神', '坚持真理', '批判思维'],
    readingTip: '讨论"说出真相的勇气"和"被误解时如何坚持"。',
    tags: ['凯迪克奖', '科学家传记', '绘本']
  },
  {
    id: 'w-010',
    title: 'The Wonders of Nature',
    author: 'Ben Hoare',
    category: 'nature',
    subCategory: '自然奇观',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['W', 'I'],
    publisher: 'DK Publishing',
    pages: 224,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: 'DK出品的自然奇观百科，展示100种令人惊叹的自然现象和生物。',
    keyTakeaways: ['自然之美', '生物多样性', '环保意识'],
    readingTip: '每周选一个主题进行深入研究，培养专题学习能力。',
    tags: ['DK', '自然百科', '英文原版']
  },
]

// I维度（探究力/科学思维）书籍 - 10本
const WILDER_I_BOOKS: Book[] = [
  {
    id: 'i-001',
    title: '可怕的科学系列',
    author: '尼克·阿诺德',
    category: 'science',
    subCategory: '趣味科学',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['I', 'W'],
    publisher: '北京少年儿童出版社',
    pages: 160,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '英国经典科普系列，用幽默方式讲解物理、化学、生物等科学原理。',
    keyTakeaways: ['科学原理', '实验精神', '幽默理解'],
    readingTip: '书中有很多可操作的小实验，建议亲子一起动手做。',
    tags: ['趣味科学', '英国经典', '实验']
  },
  {
    id: 'i-002',
    title: '费曼物理学讲义（普及版）',
    author: '理查德·费曼',
    category: 'science',
    subCategory: '物理学',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['I', 'W', 'R'],
    publisher: '上海科学技术出版社',
    pages: 500,
    difficulty: 'hard',
    rating: 9.5,
    synopsis: '诺贝尔物理学奖得主费曼的经典物理学讲义，以独特视角解读物理世界。',
    keyTakeaways: ['物理思维', '科学方法', '批判精神'],
    readingTip: '适合对物理有浓厚兴趣的学生，建议分章节慢慢消化。',
    tags: ['物理学', '费曼', '经典']
  },
  {
    id: 'i-003',
    title: '实验是最好的老师',
    author: '刘墉',
    category: 'science',
    subCategory: '科学实验',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['I', 'D'],
    publisher: '接力出版社',
    pages: 200,
    difficulty: 'easy',
    rating: 8.8,
    synopsis: '50个可以在家完成的科学实验，培养动手能力和科学探究精神。',
    keyTakeaways: ['实验技能', '观察力', '科学方法'],
    readingTip: '和孩子一起动手做实验，记录实验过程和发现。',
    tags: ['科学实验', '动手操作', '家庭科学']
  },
  {
    id: 'i-004',
    title: 'The Book of Potentially Catastrophic Science',
    author: 'Sean Connolly',
    category: 'science',
    subCategory: '科学史',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'W', 'D'],
    publisher: 'Workman Publishing',
    pages: 320,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: '通过50个可以在家做的实验，重现改变世界的科学发现时刻。',
    keyTakeaways: ['科学史', '实验复现', '科学家精神'],
    readingTip: '了解每个实验背后的科学家故事，再亲手重现发现过程。',
    tags: ['科学实验', '科学史', '英文原版']
  },
  {
    id: 'i-005',
    title: '自然科学基础知识系列',
    author: '阿西莫夫',
    category: 'science',
    subCategory: '综合科普',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['I', 'W'],
    publisher: '科学出版社',
    pages: 400,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '科幻大师阿西莫夫撰写的科普经典，系统介绍物理、化学、生物、天文等基础知识。',
    keyTakeaways: ['科学体系', '知识框架', '科学写作'],
    readingTip: '作为科学知识的"骨架"阅读，再用其他书籍补充细节。',
    tags: ['阿西莫夫', '科普经典', '系统性']
  },
  {
    id: 'i-006',
    title: '给孩子的科学实验室',
    author: '美国国家地理',
    category: 'science',
    subCategory: '科学实验',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['I', 'D', 'W'],
    publisher: '中信出版社',
    pages: 160,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: '25个有趣的科学实验，使用常见材料，培养孩子的探究精神。',
    keyTakeaways: ['实验技能', '科学方法', '动手能力'],
    readingTip: '从最简单的实验开始，逐渐增加复杂度和挑战性。',
    tags: ['国家地理', '科学实验', '低龄友好']
  },
  {
    id: 'i-007',
    title: '科学探索者系列',
    author: '美国培生集团',
    category: 'science',
    subCategory: '综合科学',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'W'],
    publisher: '浙江教育出版社',
    pages: 300,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '美国中学科学教材改编，涵盖地球科学、生命科学、物质科学等领域。',
    keyTakeaways: ['科学素养', '探究方法', '学科知识'],
    readingTip: '可以作为课外科学学习的系统补充教材。',
    tags: ['美国教材', '科学素养', '系统性']
  },
  {
    id: 'i-008',
    title: '像科学家一样思考',
    author: '温迪·苏伊',
    category: 'thinking',
    subCategory: '科学思维',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['I', 'R'],
    publisher: '中国青年出版社',
    pages: 240,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: '介绍科学研究的基本方法：假设、实验、观察、推理、验证。',
    keyTakeaways: ['科学方法', '逻辑推理', '验证思维'],
    readingTip: '用书中方法分析日常问题，培养科学思维习惯。',
    tags: ['科学方法', '思维训练', '逻辑']
  },
  {
    id: 'i-009',
    title: '这就是化学系列',
    author: '米勒等',
    category: 'science',
    subCategory: '化学',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['I', 'W'],
    publisher: '北京联合出版公司',
    pages: 180,
    difficulty: 'easy',
    rating: 8.8,
    synopsis: '用漫画和故事形式讲解化学基础知识，让化学变得有趣易懂。',
    keyTakeaways: ['化学基础', '分子世界', '物质变化'],
    readingTip: '可以配合厨房化学实验，让孩子体验化学变化。',
    tags: ['化学启蒙', '漫画科普', '趣味学习']
  },
  {
    id: 'i-010',
    title: 'Ada Twist, Scientist',
    author: 'Andrea Beaty',
    category: 'story',
    subCategory: '科学故事',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['I', 'W', 'R'],
    publisher: 'Abrams Books',
    pages: 40,
    difficulty: 'easy',
    rating: 9.3,
    synopsis: '绘本故事，讲述小女孩Ada对科学的热爱和不断提问探索的精神。',
    keyTakeaways: ['好奇心', '坚持探索', '科学精神'],
    readingTip: '鼓励孩子像Ada一样提出问题并尝试找答案。',
    tags: ['STEM绘本', '女性科学家', '英文原版']
  },
]

// L维度（生命感知力/自然联结）书籍 - 10本
const WILDER_L_BOOKS: Book[] = [
  {
    id: 'l-001',
    title: '所罗门王的指环',
    author: '康拉德·洛伦茨',
    category: 'nature',
    subCategory: '动物行为学',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['L', 'W', 'I'],
    publisher: '中信出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 9.3,
    synopsis: '诺贝尔奖得主洛伦茨的动物行为学经典，讲述与动物交流的奇妙经历。',
    keyTakeaways: ['动物行为', '人与动物关系', '观察力'],
    readingTip: '引导孩子观察身边的动物，尝试理解它们的"语言"。',
    tags: ['动物行为学', '诺贝尔奖', '经典']
  },
  {
    id: 'l-002',
    title: '寂静的春天',
    author: '蕾切尔·卡逊',
    category: 'nature',
    subCategory: '环境保护',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['L', 'R', 'W'],
    publisher: '上海译文出版社',
    pages: 320,
    difficulty: 'medium',
    rating: 9.1,
    synopsis: '开启现代环保运动的里程碑之作，揭示农药对生态系统的危害。',
    keyTakeaways: ['环保意识', '生态系统', '责任感'],
    readingTip: '讨论人类活动对环境的影响，思考我们能做什么。',
    tags: ['环保经典', '生态', '里程碑']
  },
  {
    id: 'l-003',
    title: '瓦尔登湖',
    author: '亨利·大卫·梭罗',
    category: 'nature',
    subCategory: '自然散文',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['L', 'R', 'W'],
    publisher: '上海译文出版社',
    pages: 350,
    difficulty: 'hard',
    rating: 9.0,
    synopsis: '梭罗在瓦尔登湖畔两年的隐居生活记录，探讨人与自然的关系。',
    keyTakeaways: ['简朴生活', '自然哲学', '独立思考'],
    readingTip: '选择精华章节阅读，配合户外活动体验自然。',
    tags: ['自然文学', '经典', '哲学']
  },
  {
    id: 'l-004',
    title: '植物知道生命的答案',
    author: '丹尼尔·查莫维茨',
    category: 'nature',
    subCategory: '植物学',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['L', 'I', 'W'],
    publisher: '长江文艺出版社',
    pages: 220,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: '揭示植物令人惊叹的感知能力：它们能看、闻、触、听和记忆。',
    keyTakeaways: ['植物智慧', '生命感知', '科学发现'],
    readingTip: '对照书中内容观察家中植物，验证它们的"感知"能力。',
    tags: ['植物科学', '生命智慧', '科普']
  },
  {
    id: 'l-005',
    title: '动物农场',
    author: '乔治·奥威尔',
    category: 'story',
    subCategory: '寓言故事',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['L', 'R'],
    publisher: '上海译文出版社',
    pages: 150,
    difficulty: 'medium',
    rating: 9.2,
    synopsis: '以动物为主角的政治寓言，深刻揭示权力与腐败的本质。',
    keyTakeaways: ['批判思维', '社会理解', '寓言智慧'],
    readingTip: '讨论故事的隐喻含义，培养批判性思考能力。',
    tags: ['寓言', '政治', '经典文学']
  },
  {
    id: 'l-006',
    title: '野性的呼唤',
    author: '杰克·伦敦',
    category: 'story',
    subCategory: '动物小说',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['L', 'W', 'R'],
    publisher: '译林出版社',
    pages: 200,
    difficulty: 'medium',
    rating: 9.1,
    synopsis: '狗Buck从宠物变成荒野领袖的故事，探讨本能与文明的冲突。',
    keyTakeaways: ['生存本能', '适应能力', '自然法则'],
    readingTip: '讨论"野性"与"文明"的关系，以及人与自然的联结。',
    tags: ['动物小说', '杰克伦敦', '经典']
  },
  {
    id: 'l-007',
    title: 'The Tree Lady',
    author: 'H. Joseph Hopkins',
    category: 'biography',
    subCategory: '环保人物',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['L', 'E', 'W'],
    publisher: 'Beach Lane Books',
    pages: 40,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '讲述Kate Sessions如何将圣地亚哥从沙漠变成绿洲的真实故事。',
    keyTakeaways: ['环保行动', '坚持理想', '改变世界'],
    readingTip: '讨论"一个人能改变什么"，激发环保行动意识。',
    tags: ['绘本', '环保人物', '真实故事']
  },
  {
    id: 'l-008',
    title: '一片叶子落下来',
    author: '利奥·巴斯卡利亚',
    category: 'story',
    subCategory: '生命教育',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['L', 'R'],
    publisher: '南海出版公司',
    pages: 40,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '以一片叶子的生命历程，讲述生命、死亡和轮回的哲理。',
    keyTakeaways: ['生命教育', '自然规律', '哲学启蒙'],
    readingTip: '适合在秋天阅读，结合落叶讨论生命的意义。',
    tags: ['生命教育', '哲理绘本', '四季']
  },
  {
    id: 'l-009',
    title: '大自然的社交网络',
    author: '彼得·沃莱本',
    category: 'nature',
    subCategory: '生态学',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['L', 'I', 'W'],
    publisher: '北京联合出版公司',
    pages: 260,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '揭示自然界中动植物之间令人惊叹的联系与合作网络。',
    keyTakeaways: ['生态系统', '物种联结', '自然智慧'],
    readingTip: '观察身边的生态联系，如花与蜜蜂、树与鸟的关系。',
    tags: ['生态学', '自然联结', '科普']
  },
  {
    id: 'l-010',
    title: '树木之歌',
    author: '戴维·乔治·哈斯凯尔',
    category: 'nature',
    subCategory: '自然观察',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['L', 'W', 'R'],
    publisher: '商务印书馆',
    pages: 350,
    difficulty: 'medium',
    rating: 9.1,
    synopsis: '作者倾听世界各地12棵树的声音，探讨人与自然的关系。',
    keyTakeaways: ['倾听自然', '生态联结', '全球视野'],
    readingTip: '选择身边一棵树进行长期观察，记录它的变化。',
    tags: ['自然写作', '树木', '全球视野']
  },
]

// D维度（科创力/设计思维）书籍 - 10本
const WILDER_D_BOOKS: Book[] = [
  {
    id: 'd-001',
    title: '创客：新工业革命',
    author: '克里斯·安德森',
    category: 'science',
    subCategory: '创客文化',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['D', 'I', 'W'],
    publisher: '中信出版社',
    pages: 300,
    difficulty: 'medium',
    rating: 8.8,
    synopsis: '介绍创客运动如何改变制造业和创新方式，激发动手创造热情。',
    keyTakeaways: ['创客精神', '动手创造', '创新思维'],
    readingTip: '读完后可以尝试用简单材料做一个自己的"发明"。',
    tags: ['创客', '创新', '制造']
  },
  {
    id: 'd-002',
    title: '乐高创意指南',
    author: '丹尼尔·利普科维茨',
    category: 'art',
    subCategory: '创意设计',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['D', 'W'],
    publisher: '人民邮电出版社',
    pages: 300,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '乐高官方创意指南，教你用乐高积木创造各种神奇作品。',
    keyTakeaways: ['创意思维', '空间建构', '动手能力'],
    readingTip: '不要只复制书中作品，尝试创造自己的原创设计。',
    tags: ['乐高', '创意', '动手']
  },
  {
    id: 'd-003',
    title: '设计思维：创新实践指南',
    author: '蒂姆·布朗',
    category: 'thinking',
    subCategory: '设计思维',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['D', 'I', 'E'],
    publisher: '浙江人民出版社',
    pages: 260,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: 'IDEO创始人分享设计思维方法，教你用设计师的方式解决问题。',
    keyTakeaways: ['设计思维', '以人为中心', '原型迭代'],
    readingTip: '用书中方法解决一个身边的小问题，体验设计流程。',
    tags: ['设计思维', 'IDEO', '创新方法']
  },
  {
    id: 'd-004',
    title: '编程猫Scratch创意编程',
    author: '编程猫团队',
    category: 'science',
    subCategory: '编程',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['D', 'I'],
    publisher: '人民邮电出版社',
    pages: 200,
    difficulty: 'easy',
    rating: 8.7,
    synopsis: '用Scratch图形化编程创作游戏、动画和故事的入门指南。',
    keyTakeaways: ['编程思维', '创意表达', '逻辑能力'],
    readingTip: '边读边做，每个项目都实际编程实现，才能真正掌握。',
    tags: ['Scratch', '编程入门', '创意编程']
  },
  {
    id: 'd-005',
    title: 'Rosie Revere, Engineer',
    author: 'Andrea Beaty',
    category: 'story',
    subCategory: '工程故事',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['D', 'R', 'W'],
    publisher: 'Abrams Books',
    pages: 40,
    difficulty: 'easy',
    rating: 9.2,
    synopsis: '小女孩Rosie热爱发明创造，学会从失败中汲取力量的绘本故事。',
    keyTakeaways: ['不怕失败', '工程思维', '坚持创造'],
    readingTip: '讨论"失败是成功之母"，鼓励孩子大胆尝试。',
    tags: ['STEM绘本', '女性工程师', '失败学习']
  },
  {
    id: 'd-006',
    title: '小小机械工程师',
    author: 'DK出版社',
    category: 'science',
    subCategory: '机械工程',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['D', 'I'],
    publisher: '电子工业出版社',
    pages: 180,
    difficulty: 'easy',
    rating: 8.8,
    synopsis: '通过25个动手项目学习简单机械原理，培养工程思维。',
    keyTakeaways: ['简单机械', '工程设计', '动手能力'],
    readingTip: '收集废旧材料做书中的项目，体验工程师的乐趣。',
    tags: ['DK', '机械工程', '动手项目']
  },
  {
    id: 'd-007',
    title: '发明大王爱迪生的实验室',
    author: '塔玛拉·赖利',
    category: 'biography',
    subCategory: '发明家',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['D', 'I', 'W'],
    publisher: '中信出版社',
    pages: 150,
    difficulty: 'easy',
    rating: 8.9,
    synopsis: '讲述爱迪生的发明故事，并提供可以在家做的相关实验。',
    keyTakeaways: ['发明精神', '实验方法', '坚持不懈'],
    readingTip: '重点了解爱迪生如何从失败中学习，培养成长型思维。',
    tags: ['发明家', '爱迪生', '实验']
  },
  {
    id: 'd-008',
    title: '3D打印从入门到精通',
    author: '林慧龙',
    category: 'science',
    subCategory: '3D打印',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['D', 'I'],
    publisher: '清华大学出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 8.6,
    synopsis: '系统介绍3D打印技术和建模方法，适合青少年创客入门。',
    keyTakeaways: ['3D打印', '数字建模', '创客技能'],
    readingTip: '如果没有3D打印机，可以先用免费软件学习建模。',
    tags: ['3D打印', '数字制造', '创客']
  },
  {
    id: 'd-009',
    title: 'Arduino创意电子制作',
    author: '麦克·库克',
    category: 'science',
    subCategory: '电子制作',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['D', 'I'],
    publisher: '人民邮电出版社',
    pages: 320,
    difficulty: 'medium',
    rating: 8.8,
    synopsis: '通过Arduino开发板学习电子制作和编程的入门指南。',
    keyTakeaways: ['电子制作', '编程控制', '项目设计'],
    readingTip: '从最简单的LED项目开始，逐步挑战复杂项目。',
    tags: ['Arduino', '电子制作', '编程']
  },
  {
    id: 'd-010',
    title: '世界上最美的创意折纸',
    author: '布瑞安·陈',
    category: 'art',
    subCategory: '折纸艺术',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['D', 'E'],
    publisher: '湖南科学技术出版社',
    pages: 160,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '融合数学和艺术的折纸指南，从简单到复杂的精美作品。',
    keyTakeaways: ['空间思维', '精细动作', '艺术创造'],
    readingTip: '先从简单折纸开始，逐步挑战复杂的立体作品。',
    tags: ['折纸', '艺术', '数学']
  },
]

// E维度（生态责任力/表达沟通）书籍 - 10本
const WILDER_E_BOOKS: Book[] = [
  {
    id: 'e-001',
    title: '演讲的力量',
    author: '克里斯·安德森',
    category: 'communication',
    subCategory: '演讲技巧',
    targetAudience: 'both',
    ageRange: '12-14',
    wilderDimensions: ['E', 'R'],
    publisher: '中信出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: 'TED掌门人分享演讲秘诀，教你如何传递想法、打动听众。',
    keyTakeaways: ['演讲技巧', '故事讲述', '观点表达'],
    readingTip: '选一个感兴趣的话题，用书中方法准备一个小演讲。',
    tags: ['演讲', 'TED', '表达能力']
  },
  {
    id: 'e-002',
    title: '青少年沟通圣经',
    author: '约翰·麦克斯韦尔',
    category: 'communication',
    subCategory: '沟通技巧',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['E', 'L'],
    publisher: '中信出版社',
    pages: 220,
    difficulty: 'easy',
    rating: 8.7,
    synopsis: '专为青少年设计的沟通指南，培养有效表达和倾听能力。',
    keyTakeaways: ['沟通技巧', '倾听能力', '人际关系'],
    readingTip: '每学一个技巧就在日常中练习，形成沟通好习惯。',
    tags: ['沟通', '青少年', '人际关系']
  },
  {
    id: 'e-003',
    title: '写作这回事',
    author: '斯蒂芬·金',
    category: 'art',
    subCategory: '写作技巧',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['E', 'R', 'W'],
    publisher: '上海文艺出版社',
    pages: 350,
    difficulty: 'medium',
    rating: 9.1,
    synopsis: '畅销书作家斯蒂芬·金分享写作心得，既是技巧指导也是回忆录。',
    keyTakeaways: ['写作技巧', '阅读重要性', '坚持写作'],
    readingTip: '每天写点东西，不管好坏，坚持是最重要的。',
    tags: ['写作', '斯蒂芬金', '创作']
  },
  {
    id: 'e-004',
    title: '儿童写作课',
    author: '蒋军晶',
    category: 'education',
    subCategory: '写作教育',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['E', 'W'],
    publisher: '中国人民大学出版社',
    pages: 260,
    difficulty: 'easy',
    rating: 8.9,
    synopsis: '特级教师的儿童写作指导，用游戏和故事激发写作兴趣。',
    keyTakeaways: ['写作入门', '素材积累', '表达技巧'],
    readingTip: '跟着书中的练习写作，不要追求完美，先写起来。',
    tags: ['儿童写作', '作文', '教育']
  },
  {
    id: 'e-005',
    title: '可持续发展教育指南',
    author: '联合国教科文组织',
    category: 'education',
    subCategory: '环境教育',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['E', 'L', 'R'],
    publisher: '人民教育出版社',
    pages: 200,
    difficulty: 'medium',
    rating: 8.6,
    synopsis: '介绍可持续发展目标，引导青少年思考和行动。',
    keyTakeaways: ['可持续发展', '全球公民', '行动力'],
    readingTip: '选择一个可持续发展目标，制定个人行动计划。',
    tags: ['SDGs', '环境教育', '全球公民']
  },
  {
    id: 'e-006',
    title: '孩子的绿色地球',
    author: '大卫·铃木',
    category: 'nature',
    subCategory: '环境保护',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['E', 'L', 'W'],
    publisher: '二十一世纪出版社',
    pages: 150,
    difficulty: 'easy',
    rating: 8.8,
    synopsis: '环保科学家为孩子写的地球保护指南，附有可操作的行动建议。',
    keyTakeaways: ['环保行动', '地球保护', '小事做起'],
    readingTip: '和孩子一起制定家庭环保计划，从小事做起。',
    tags: ['环保', '儿童读物', '行动指南']
  },
  {
    id: 'e-007',
    title: 'Speak Up!',
    author: 'Laura Duksta',
    category: 'story',
    subCategory: '表达勇气',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['E', 'R'],
    publisher: 'Sourcebooks Jabberwocky',
    pages: 32,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '鼓励孩子勇敢表达自己想法和感受的温暖绘本。',
    keyTakeaways: ['勇敢表达', '自我价值', '声音力量'],
    readingTip: '鼓励孩子分享读后感，练习表达自己的想法。',
    tags: ['绘本', '表达勇气', '自信']
  },
  {
    id: 'e-008',
    title: '绿色新政：为什么需要它，如何实现它',
    author: '杰里米·里夫金',
    category: 'science',
    subCategory: '环境政策',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['E', 'I', 'R'],
    publisher: '中信出版社',
    pages: 320,
    difficulty: 'hard',
    rating: 8.7,
    synopsis: '探讨气候变化与可持续发展的解决方案，培养全球视野。',
    keyTakeaways: ['气候变化', '可再生能源', '系统思维'],
    readingTip: '适合对环境问题有兴趣的高年级学生深度阅读。',
    tags: ['气候变化', '可持续发展', '政策']
  },
  {
    id: 'e-009',
    title: '中国少年儿童演讲与口才训练',
    author: '文若愚',
    category: 'communication',
    subCategory: '口才训练',
    targetAudience: 'child',
    ageRange: '8-10',
    wilderDimensions: ['E', 'R'],
    publisher: '中国华侨出版社',
    pages: 240,
    difficulty: 'easy',
    rating: 8.5,
    synopsis: '系统的少儿口才训练教程，包含绕口令、故事讲述、即兴演讲等。',
    keyTakeaways: ['口才训练', '表达技巧', '自信心'],
    readingTip: '每天练习10分钟，持续训练比集中训练更有效。',
    tags: ['口才', '演讲', '训练']
  },
  {
    id: 'e-010',
    title: '写给孩子的环保书',
    author: '罗伊·亚当斯',
    category: 'nature',
    subCategory: '环境保护',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['E', 'L'],
    publisher: '北京联合出版公司',
    pages: 120,
    difficulty: 'easy',
    rating: 8.8,
    synopsis: '用孩子能理解的语言讲解环保知识，培养环保意识和行动力。',
    keyTakeaways: ['环保知识', '日常行动', '责任感'],
    readingTip: '读完后和孩子一起做一件环保小事，如垃圾分类。',
    tags: ['环保', '低龄友好', '行动指南']
  },
]

// R维度（团队韧性力/反思成长）书籍 - 10本
const WILDER_R_BOOKS: Book[] = [
  {
    id: 'r-001',
    title: '刻意练习',
    author: '安德斯·艾利克森',
    category: 'psychology',
    subCategory: '学习方法',
    targetAudience: 'both',
    ageRange: '12-14',
    wilderDimensions: ['R', 'D', 'I'],
    publisher: '机械工业出版社',
    pages: 300,
    difficulty: 'medium',
    rating: 9.0,
    synopsis: '揭示天才背后的秘密：正确的练习方法比天赋更重要。',
    keyTakeaways: ['刻意练习', '反馈循环', '成长型思维'],
    readingTip: '选择一个想提升的技能，用刻意练习的方法训练。',
    tags: ['学习方法', '专业技能', '成长']
  },
  {
    id: 'r-002',
    title: '心态：新成功心理学',
    author: '卡罗尔·德韦克',
    category: 'psychology',
    subCategory: '成长型思维',
    targetAudience: 'both',
    ageRange: '10-12',
    wilderDimensions: ['R', 'W'],
    publisher: '江西人民出版社',
    pages: 280,
    difficulty: 'easy',
    rating: 9.2,
    synopsis: '成长型思维的原创研究者详解两种思维模式及其影响。',
    keyTakeaways: ['成长型思维', '固定型思维', '努力价值'],
    readingTip: '识别自己和孩子的思维模式，用"还没有"代替"不会"。',
    tags: ['成长型思维', '心理学', '教育']
  },
  {
    id: 'r-003',
    title: '反脆弱',
    author: '纳西姆·塔勒布',
    category: 'thinking',
    subCategory: '思维模式',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['R', 'I', 'W'],
    publisher: '中信出版社',
    pages: 450,
    difficulty: 'hard',
    rating: 8.9,
    synopsis: '探讨如何从不确定性和压力中获益，培养反脆弱能力。',
    keyTakeaways: ['反脆弱', '不确定性', '韧性'],
    readingTip: '内容较深，可选读核心章节，理解"反脆弱"概念。',
    tags: ['反脆弱', '思维', '塔勒布']
  },
  {
    id: 'r-004',
    title: '坚毅：释放激情与坚持的力量',
    author: '安杰拉·达克沃斯',
    category: 'psychology',
    subCategory: '坚毅品质',
    targetAudience: 'both',
    ageRange: '10-12',
    wilderDimensions: ['R', 'D'],
    publisher: '中信出版社',
    pages: 320,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: '宾大心理学教授揭示"坚毅"比天赋更能预测成功。',
    keyTakeaways: ['坚毅品质', '长期目标', '热情+坚持'],
    readingTip: '和孩子讨论什么是值得坚持的事情，培养坚毅品质。',
    tags: ['坚毅', 'grit', '成功心理']
  },
  {
    id: 'r-005',
    title: '失败力：如何将失败转化为成功',
    author: '约翰·C.麦克斯韦尔',
    category: 'psychology',
    subCategory: '失败学习',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['R', 'W'],
    publisher: '中信出版社',
    pages: 240,
    difficulty: 'easy',
    rating: 8.8,
    synopsis: '教你如何正确看待失败，将失败转化为成长的机会。',
    keyTakeaways: ['失败学习', '韧性', '成长'],
    readingTip: '分享自己的失败故事，和孩子一起分析学到了什么。',
    tags: ['失败学习', '韧性', '成长']
  },
  {
    id: 'r-006',
    title: '最好的我们',
    author: '八月长安',
    category: 'story',
    subCategory: '成长小说',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['R', 'L'],
    publisher: '湖南文艺出版社',
    pages: 360,
    difficulty: 'easy',
    rating: 9.0,
    synopsis: '讲述青春期成长的故事，探讨友情、梦想和自我认知。',
    keyTakeaways: ['青春成长', '友情', '自我认同'],
    readingTip: '适合初中生阅读，可以讨论书中人物的成长和选择。',
    tags: ['青春小说', '成长', '校园']
  },
  {
    id: 'r-007',
    title: 'The Girl Who Never Made Mistakes',
    author: 'Mark Pett',
    category: 'story',
    subCategory: '成长绘本',
    targetAudience: 'child',
    ageRange: '6-8',
    wilderDimensions: ['R', 'W'],
    publisher: 'Sourcebooks Jabberwocky',
    pages: 32,
    difficulty: 'easy',
    rating: 9.1,
    synopsis: '一个从不犯错的女孩学会接受错误的故事，培养健康的失败观。',
    keyTakeaways: ['接受错误', '完美主义', '成长'],
    readingTip: '讨论"犯错也没关系"，帮助孩子减轻对失败的恐惧。',
    tags: ['绘本', '错误', '成长']
  },
  {
    id: 'r-008',
    title: '团队的五大障碍',
    author: '帕特里克·兰西奥尼',
    category: 'psychology',
    subCategory: '团队合作',
    targetAudience: 'child',
    ageRange: '14+',
    wilderDimensions: ['R', 'L', 'E'],
    publisher: '中信出版社',
    pages: 220,
    difficulty: 'medium',
    rating: 8.9,
    synopsis: '用寓言故事讲解团队合作的五大障碍及解决方法。',
    keyTakeaways: ['团队合作', '信任', '冲突处理'],
    readingTip: '可以在小组项目中应用书中的团队合作原则。',
    tags: ['团队', '领导力', '寓言']
  },
  {
    id: 'r-009',
    title: '哲学家的工具箱',
    author: '朱利安·巴吉尼',
    category: 'thinking',
    subCategory: '批判思维',
    targetAudience: 'child',
    ageRange: '12-14',
    wilderDimensions: ['R', 'I'],
    publisher: '中国人民大学出版社',
    pages: 280,
    difficulty: 'medium',
    rating: 8.8,
    synopsis: '介绍100个批判性思维工具，培养逻辑思考和反思能力。',
    keyTakeaways: ['批判思维', '逻辑谬误', '论证分析'],
    readingTip: '学习识别日常中的逻辑谬误，培养理性思维。',
    tags: ['批判思维', '逻辑', '哲学']
  },
  {
    id: 'r-010',
    title: '谁动了我的奶酪（青少版）',
    author: '斯宾塞·约翰逊',
    category: 'story',
    subCategory: '寓言故事',
    targetAudience: 'child',
    ageRange: '10-12',
    wilderDimensions: ['R', 'W'],
    publisher: '中信出版社',
    pages: 100,
    difficulty: 'easy',
    rating: 8.7,
    synopsis: '用简单的寓言故事讲述如何适应变化，培养变化应对能力。',
    keyTakeaways: ['适应变化', '主动行动', '克服恐惧'],
    readingTip: '讨论生活中的"变化"，如何像故事中的角色那样应对。',
    tags: ['寓言', '变化', '适应力']
  },
]

// ========== 合并所有书籍 ==========
export const BOOK_DATABASE: Book[] = [
  ...CHILDREN_SCIENCE_BOOKS,
  ...CHILDREN_THINKING_BOOKS,
  ...CHILDREN_BIOGRAPHY_BOOKS,
  ...PARENT_EDUCATION_BOOKS,
  ...PARENT_PSYCHOLOGY_BOOKS,
  ...WILDER_W_BOOKS,
  ...WILDER_I_BOOKS,
  ...WILDER_L_BOOKS,
  ...WILDER_D_BOOKS,
  ...WILDER_E_BOOKS,
  ...WILDER_R_BOOKS,
]

// ========== 工具函数 ==========

export type BookCategory = Book['category']
export type BookAgeRange = Book['ageRange']
export type TargetAudience = Book['targetAudience']
export type WilderDim = 'W' | 'I' | 'L' | 'D' | 'E' | 'R'

// 获取儿童书籍
export function getChildBooks(age: number): Book[] {
  return BOOK_DATABASE.filter(b => {
    return (b.targetAudience === 'child' || b.targetAudience === 'both') &&
      isBookAgeAppropriate(age, b.ageRange)
  })
}

// 获取家长书籍
export function getParentBooks(): Book[] {
  return BOOK_DATABASE.filter(b => 
    b.targetAudience === 'parent' || b.targetAudience === 'both'
  )
}

// 按WILDER维度匹配书籍
export function getBooksByWilder(
  topDimensions: WilderDim[],
  targetAudience: TargetAudience,
  age?: number,
  limit: number = 10
): Book[] {
  return BOOK_DATABASE
    .filter(b => {
      const audienceMatch = targetAudience === 'both' || b.targetAudience === targetAudience || b.targetAudience === 'both'
      const dimMatch = b.wilderDimensions.some(dim => topDimensions.includes(dim))
      const ageMatch = targetAudience === 'parent' || !age || isBookAgeAppropriate(age, b.ageRange)
      return audienceMatch && dimMatch && ageMatch
    })
    .sort((a, b) => {
      const aMatches = a.wilderDimensions.filter(dim => topDimensions.includes(dim)).length
      const bMatches = b.wilderDimensions.filter(dim => topDimensions.includes(dim)).length
      if (aMatches !== bMatches) return bMatches - aMatches
      return b.rating - a.rating
    })
    .slice(0, limit)
}

// 按分类获取书籍
export function getBooksByCategory(category: BookCategory): Book[] {
  return BOOK_DATABASE.filter(b => b.category === category)
}

// 获取推荐书籍（综合匹配）
export function getRecommendedBooks(
  topDimensions: WilderDim[],
  age: number
): { childBooks: Book[]; parentBooks: Book[] } {
  const childBooks = getBooksByWilder(topDimensions, 'child', age, 10)
  const parentBooks = getBooksByWilder(topDimensions, 'parent', undefined, 6)
  return { childBooks, parentBooks }
}

// 按年龄段获取书籍
function isBookAgeAppropriate(age: number, bookAge: BookAgeRange): boolean {
  if (bookAge === 'adult') return false
  const [min, max] = bookAge.split('-').map(s => parseInt(s.replace('+', '')))
  if (bookAge.includes('+')) return age >= min
  return age >= min && age <= (max || min + 2)
}

// 获取书籍统计
export function getBookStats(): {
  total: number
  byAudience: Record<TargetAudience, number>
  byCategory: Record<BookCategory, number>
} {
  const byAudience: Record<TargetAudience, number> = { child: 0, parent: 0, both: 0 }
  const byCategory: Record<BookCategory, number> = {
    science: 0, nature: 0, thinking: 0, story: 0, biography: 0,
    art: 0, psychology: 0, education: 0, parenting: 0, communication: 0
  }
  for (const book of BOOK_DATABASE) {
    byAudience[book.targetAudience]++
    byCategory[book.category]++
  }
  return { total: BOOK_DATABASE.length, byAudience, byCategory }
}

// 搜索书籍
export function searchBooks(query: string): Book[] {
  const lowerQuery = query.toLowerCase()
  return BOOK_DATABASE.filter(b =>
    b.title.toLowerCase().includes(lowerQuery) ||
    b.author.toLowerCase().includes(lowerQuery) ||
    b.tags.some(t => t.toLowerCase().includes(lowerQuery)) ||
    b.synopsis.toLowerCase().includes(lowerQuery)
  )
}
