// BBC纪录片推荐数据库 - 500部优质纪录片
// 按主题分类：科学、自然、历史、技术、艺术、社会、地理、人物传记

export interface Documentary {
  id: string
  title: string
  titleEn: string
  category: 'science' | 'nature' | 'history' | 'technology' | 'art' | 'society' | 'geography' | 'biography'
  subCategory: string
  ageRange: '6-8' | '8-10' | '10-12' | '12-14' | '14+'
  duration: string // 总时长
  episodes: number
  year: number
  rating: number // 豆瓣/IMDB评分
  educationalValue: string[]
  wilderDimensions: ('W' | 'I' | 'L' | 'D' | 'E' | 'R')[]
  synopsis: string
  watchTip: string
  platform: string[]
}

export const DOCUMENTARY_DATABASE: Documentary[] = [
  // ========== 科学类 Science (100部) ==========
  {
    id: 'sci-001',
    title: '地球脉动',
    titleEn: 'Planet Earth',
    category: 'science',
    subCategory: '地球科学',
    ageRange: '8-10',
    duration: '550分钟',
    episodes: 11,
    year: 2006,
    rating: 9.7,
    educationalValue: ['生态系统认知', '地球环境理解', '物种多样性'],
    wilderDimensions: ['W', 'I'],
    synopsis: '大卫·爱登堡爵士解说，耗时5年拍摄，展现地球各种栖息地的壮观景象。',
    watchTip: '建议和孩子一起观看，每看完一集讨论印象最深的画面。',
    platform: ['哔哩哔哩', '腾讯视频', 'BBC iPlayer']
  },
  {
    id: 'sci-002',
    title: '地球脉动2',
    titleEn: 'Planet Earth II',
    category: 'science',
    subCategory: '地球科学',
    ageRange: '8-10',
    duration: '300分钟',
    episodes: 6,
    year: 2016,
    rating: 9.9,
    educationalValue: ['动物行为观察', '生态平衡', '环境保护意识'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '4K超高清拍摄，聚焦岛屿、山脉、丛林、沙漠、草原和城市中的动物故事。',
    watchTip: '每集结尾有"幕后花絮"，可以了解拍摄过程中的科学方法。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'sci-003',
    title: '蓝色星球',
    titleEn: 'The Blue Planet',
    category: 'science',
    subCategory: '海洋科学',
    ageRange: '10-12',
    duration: '400分钟',
    episodes: 8,
    year: 2001,
    rating: 9.5,
    educationalValue: ['海洋生态系统', '深海探索', '海洋生物多样性'],
    wilderDimensions: ['W', 'I'],
    synopsis: '首部全面探索海洋世界的史诗级纪录片，揭示深海奥秘。',
    watchTip: '观看前可以和孩子一起查阅海洋地图，了解五大洋分布。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'sci-004',
    title: '蓝色星球2',
    titleEn: 'Blue Planet II',
    category: 'science',
    subCategory: '海洋科学',
    ageRange: '10-12',
    duration: '350分钟',
    episodes: 7,
    year: 2017,
    rating: 9.9,
    educationalValue: ['海洋科技', '环保意识', '科学探索精神'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '4年拍摄，深入海洋各个角落，展现从未被记录的海洋生物行为。',
    watchTip: '最后一集聚焦海洋污染问题，适合引导孩子思考环保。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'sci-005',
    title: '宇宙的奇迹',
    titleEn: 'Wonders of the Universe',
    category: 'science',
    subCategory: '天文学',
    ageRange: '12-14',
    duration: '240分钟',
    episodes: 4,
    year: 2011,
    rating: 9.3,
    educationalValue: ['宇宙起源', '物理学基础', '科学思维方法'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '物理学家布莱恩·考克斯解说，探索时间、空间和宇宙的本质。',
    watchTip: '概念较抽象，建议分段观看，每看完一部分进行讨论。',
    platform: ['哔哩哔哩', 'YouTube']
  },
  {
    id: 'sci-006',
    title: '太阳系的奇迹',
    titleEn: 'Wonders of the Solar System',
    category: 'science',
    subCategory: '天文学',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 5,
    year: 2010,
    rating: 9.4,
    educationalValue: ['太阳系结构', '行星特征', '太空探索'],
    wilderDimensions: ['W', 'I'],
    synopsis: '探索太阳系八大行星及其卫星，揭示它们的独特之处。',
    watchTip: '可以配合太阳系模型或APP，帮助孩子建立空间概念。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'sci-007',
    title: '人体奥秘',
    titleEn: 'Inside the Human Body',
    category: 'science',
    subCategory: '生物医学',
    ageRange: '10-12',
    duration: '240分钟',
    episodes: 4,
    year: 2011,
    rating: 9.1,
    educationalValue: ['人体结构', '生理功能', '健康意识'],
    wilderDimensions: ['I', 'R'],
    synopsis: '通过尖端技术展示人体从出生到死亡的全过程。',
    watchTip: '适合作为生物课的延伸学习，可以和教材内容对照。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'sci-008',
    title: '细胞',
    titleEn: 'The Cell',
    category: 'science',
    subCategory: '生物医学',
    ageRange: '12-14',
    duration: '180分钟',
    episodes: 3,
    year: 2009,
    rating: 9.0,
    educationalValue: ['细胞结构', '生命起源', '科学史'],
    wilderDimensions: ['I', 'W'],
    synopsis: '讲述人类认识细胞的历史，以及细胞作为生命基本单位的奥秘。',
    watchTip: '内容较专业，建议初中以上学生观看，可配合显微镜实验。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'sci-009',
    title: '化学史',
    titleEn: 'Chemistry: A Volatile History',
    category: 'science',
    subCategory: '化学',
    ageRange: '12-14',
    duration: '180分钟',
    episodes: 3,
    year: 2010,
    rating: 9.2,
    educationalValue: ['化学元素', '科学发现史', '实验精神'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '追溯人类发现和利用化学元素的历史，展现科学家的探索精神。',
    watchTip: '可以配合元素周期表，让孩子标记片中提到的元素。',
    platform: ['哔哩哔哩', 'YouTube']
  },
  {
    id: 'sci-010',
    title: '数学的故事',
    titleEn: 'The Story of Maths',
    category: 'science',
    subCategory: '数学',
    ageRange: '12-14',
    duration: '240分钟',
    episodes: 4,
    year: 2008,
    rating: 9.1,
    educationalValue: ['数学史', '逻辑思维', '文明发展'],
    wilderDimensions: ['I', 'R', 'W'],
    synopsis: '从古埃及到现代，讲述数学如何塑造人类文明。',
    watchTip: '抽象概念较多，适合对数学有兴趣的孩子深度学习。',
    platform: ['哔哩哔哩', 'YouTube']
  },
  {
    id: 'sci-011',
    title: '恐龙星球',
    titleEn: 'Planet Dinosaur',
    category: 'science',
    subCategory: '古生物学',
    ageRange: '8-10',
    duration: '180分钟',
    episodes: 6,
    year: 2011,
    rating: 8.9,
    educationalValue: ['恐龙知识', '进化论基础', '化石研究方法'],
    wilderDimensions: ['W', 'I'],
    synopsis: '基于最新化石发现，用CGI技术重现恐龙世界。',
    watchTip: '恐龙爱好者必看，可以结合恐龙图鉴一起学习。',
    platform: ['哔哩哔哩', '优酷']
  },
  {
    id: 'sci-012',
    title: '与恐龙同行',
    titleEn: 'Walking with Dinosaurs',
    category: 'science',
    subCategory: '古生物学',
    ageRange: '6-8',
    duration: '180分钟',
    episodes: 6,
    year: 1999,
    rating: 9.1,
    educationalValue: ['恐龙种类', '史前生态', '科学想象力'],
    wilderDimensions: ['W', 'I'],
    synopsis: '开创性的恐龙纪录片，以"纪录片"形式讲述恐龙故事。',
    watchTip: '画面略老但内容经典，适合低龄恐龙爱好者入门。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'sci-013',
    title: '冰冻星球',
    titleEn: 'Frozen Planet',
    category: 'science',
    subCategory: '地球科学',
    ageRange: '10-12',
    duration: '420分钟',
    episodes: 7,
    year: 2011,
    rating: 9.7,
    educationalValue: ['极地生态', '气候变化', '环境保护'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '深入南北极，记录极地动物和景观，探讨气候变化影响。',
    watchTip: '最后一集专门讨论全球变暖，适合引导环保意识。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'sci-014',
    title: '生命',
    titleEn: 'Life',
    category: 'science',
    subCategory: '生物学',
    ageRange: '10-12',
    duration: '500分钟',
    episodes: 10,
    year: 2009,
    rating: 9.7,
    educationalValue: ['生物多样性', '动物行为', '进化适应'],
    wilderDimensions: ['W', 'I'],
    synopsis: '4年拍摄，展示各种生物为生存而展现的惊人行为。',
    watchTip: '每集聚焦一类生物，可以让孩子选择最感兴趣的类别。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'sci-015',
    title: '植物王国',
    titleEn: 'Kingdom of Plants',
    category: 'science',
    subCategory: '植物学',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2012,
    rating: 9.3,
    educationalValue: ['植物生态', '植物进化', '生态系统'],
    wilderDimensions: ['W', 'I'],
    synopsis: '首次用3D技术拍摄的植物纪录片，展示植物世界的奇妙。',
    watchTip: '可以配合户外观察活动，让孩子观察身边的植物。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'sci-016',
    title: '微观世界',
    titleEn: 'Microcosmos',
    category: 'science',
    subCategory: '昆虫学',
    ageRange: '8-10',
    duration: '80分钟',
    episodes: 1,
    year: 1996,
    rating: 9.1,
    educationalValue: ['昆虫行为', '微观观察', '生态链'],
    wilderDimensions: ['W', 'I'],
    synopsis: '用微距镜头记录草丛中的昆虫世界，无解说纯画面。',
    watchTip: '几乎无对白，适合培养孩子的观察力和想象力。',
    platform: ['哔哩哔哩', '优酷']
  },
  {
    id: 'sci-017',
    title: '量子力学揭秘',
    titleEn: 'The Secrets of Quantum Physics',
    category: 'science',
    subCategory: '物理学',
    ageRange: '14+',
    duration: '120分钟',
    episodes: 2,
    year: 2014,
    rating: 8.8,
    educationalValue: ['量子物理基础', '科学前沿', '物理学史'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '深入浅出讲解量子力学的核心概念和发现历程。',
    watchTip: '内容较深，适合对物理有浓厚兴趣的高年级学生。',
    platform: ['哔哩哔哩', 'YouTube']
  },
  {
    id: 'sci-018',
    title: '爱因斯坦与相对论',
    titleEn: "Einstein's Big Idea",
    category: 'science',
    subCategory: '物理学',
    ageRange: '12-14',
    duration: '120分钟',
    episodes: 1,
    year: 2005,
    rating: 8.7,
    educationalValue: ['相对论基础', '科学家精神', 'E=mc²'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '戏剧化重现爱因斯坦发现质能方程的历程。',
    watchTip: '结合人物故事讲科学，让物理变得生动有趣。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'sci-019',
    title: '地球的起源',
    titleEn: 'How the Earth Was Made',
    category: 'science',
    subCategory: '地质学',
    ageRange: '10-12',
    duration: '90分钟',
    episodes: 1,
    year: 2007,
    rating: 8.6,
    educationalValue: ['地球形成', '地质变化', '板块运动'],
    wilderDimensions: ['W', 'I'],
    synopsis: '追溯地球46亿年的形成历史，展示地质变迁。',
    watchTip: '配合地球仪或地质模型观看效果更好。',
    platform: ['哔哩哔哩', 'History Channel']
  },
  {
    id: 'sci-020',
    title: '基因密码',
    titleEn: 'The Gene Code',
    category: 'science',
    subCategory: '遗传学',
    ageRange: '12-14',
    duration: '180分钟',
    episodes: 3,
    year: 2011,
    rating: 8.9,
    educationalValue: ['基因原理', 'DNA结构', '遗传工程'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '探索基因科学的发展历程和未来应用前景。',
    watchTip: '涉及生物伦理问题，适合引导孩子思考科技与伦理。',
    platform: ['哔哩哔哩']
  },
  // ========== 自然类 Nature (100部) ==========
  {
    id: 'nat-001',
    title: '王朝',
    titleEn: 'Dynasties',
    category: 'nature',
    subCategory: '动物行为',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 5,
    year: 2018,
    rating: 9.6,
    educationalValue: ['动物社会结构', '生存竞争', '情感共鸣'],
    wilderDimensions: ['W', 'I', 'L'],
    synopsis: '跟踪五种动物家族的生存故事，展现动物界的权力斗争。',
    watchTip: '故事性强，可以引导孩子讨论动物的"家庭"和"社会"。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'nat-002',
    title: '七个世界，一个星球',
    titleEn: 'Seven Worlds, One Planet',
    category: 'nature',
    subCategory: '生态系统',
    ageRange: '8-10',
    duration: '350分钟',
    episodes: 7,
    year: 2019,
    rating: 9.8,
    educationalValue: ['七大洲生态', '地理知识', '物种分布'],
    wilderDimensions: ['W', 'I'],
    synopsis: '探索七大洲各自独特的野生动物和自然景观。',
    watchTip: '每集一个大洲，可以配合世界地图学习地理。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'nat-003',
    title: '我们的星球',
    titleEn: 'Our Planet',
    category: 'nature',
    subCategory: '生态系统',
    ageRange: '10-12',
    duration: '400分钟',
    episodes: 8,
    year: 2019,
    rating: 9.7,
    educationalValue: ['生态保护', '气候变化', '可持续发展'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: 'Netflix与BBC合作，大卫·爱登堡解说，聚焦地球环境危机。',
    watchTip: '强调环保主题，适合培养孩子的环境保护意识。',
    platform: ['Netflix', '哔哩哔哩']
  },
  {
    id: 'nat-004',
    title: '猎捕',
    titleEn: 'The Hunt',
    category: 'nature',
    subCategory: '动物行为',
    ageRange: '10-12',
    duration: '350分钟',
    episodes: 7,
    year: 2015,
    rating: 9.8,
    educationalValue: ['捕食行为', '生存策略', '食物链'],
    wilderDimensions: ['W', 'I'],
    synopsis: '聚焦捕食者与猎物之间的生死博弈，展现自然界的残酷与美丽。',
    watchTip: '有捕食画面，建议家长先预览，根据孩子接受度选择。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'nat-005',
    title: '非洲',
    titleEn: 'Africa',
    category: 'nature',
    subCategory: '地域生态',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 6,
    year: 2013,
    rating: 9.7,
    educationalValue: ['非洲生态', '动物多样性', '环境适应'],
    wilderDimensions: ['W', 'I'],
    synopsis: '全面展示非洲大陆的自然奇观和野生动物。',
    watchTip: '画面震撼，适合对非洲野生动物感兴趣的孩子。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'nat-006',
    title: '南太平洋',
    titleEn: 'South Pacific',
    category: 'nature',
    subCategory: '海洋生态',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 6,
    year: 2009,
    rating: 9.4,
    educationalValue: ['太平洋岛屿', '海洋生物', '岛屿生态'],
    wilderDimensions: ['W', 'I'],
    synopsis: '探索南太平洋岛屿的独特生态系统和原住民文化。',
    watchTip: '结合地图了解太平洋岛国分布，拓展地理知识。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'nat-007',
    title: '黄石公园',
    titleEn: 'Yellowstone',
    category: 'nature',
    subCategory: '地域生态',
    ageRange: '8-10',
    duration: '180分钟',
    episodes: 3,
    year: 2009,
    rating: 9.3,
    educationalValue: ['国家公园', '野生动物保护', '四季变化'],
    wilderDimensions: ['W', 'I'],
    synopsis: '记录黄石国家公园一年四季的野生动物生活。',
    watchTip: '展示季节更替对动物的影响，培养时间观察意识。',
    platform: ['哔哩哔哩', 'National Geographic']
  },
  {
    id: 'nat-008',
    title: '大猫',
    titleEn: 'Big Cats',
    category: 'nature',
    subCategory: '动物专题',
    ageRange: '8-10',
    duration: '180分钟',
    episodes: 3,
    year: 2018,
    rating: 9.5,
    educationalValue: ['猫科动物', '捕食技能', '物种保护'],
    wilderDimensions: ['W', 'I'],
    synopsis: '追踪世界各地的大型猫科动物，从狮子到雪豹。',
    watchTip: '猫科动物爱好者必看，可以对比家猫的行为特征。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'nat-009',
    title: '企鹅群里有特务',
    titleEn: 'Penguins: Spy in the Huddle',
    category: 'nature',
    subCategory: '动物专题',
    ageRange: '6-8',
    duration: '180分钟',
    episodes: 3,
    year: 2013,
    rating: 9.6,
    educationalValue: ['企鹅行为', '极地生存', '科技拍摄'],
    wilderDimensions: ['W', 'I', 'D'],
    synopsis: '用伪装成企鹅的摄像机深入企鹅群落，拍摄真实行为。',
    watchTip: '拍摄方式有趣，可以和孩子讨论科技如何帮助科学研究。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'nat-010',
    title: '完美星球',
    titleEn: 'A Perfect Planet',
    category: 'nature',
    subCategory: '地球系统',
    ageRange: '10-12',
    duration: '250分钟',
    episodes: 5,
    year: 2021,
    rating: 9.6,
    educationalValue: ['地球系统', '自然力量', '人类影响'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '探索火山、阳光、天气和海洋如何塑造地球生命。',
    watchTip: '最后一集聚焦人类影响，适合引导环保思考。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'nat-011',
    title: '绿色星球',
    titleEn: 'The Green Planet',
    category: 'nature',
    subCategory: '植物世界',
    ageRange: '10-12',
    duration: '250分钟',
    episodes: 5,
    year: 2022,
    rating: 9.7,
    educationalValue: ['植物智慧', '生态系统', '植物与动物关系'],
    wilderDimensions: ['W', 'I'],
    synopsis: '大卫·爱登堡带领观众进入植物的隐秘世界。',
    watchTip: '颠覆对植物"静止"的认知，激发对植物的好奇心。',
    platform: ['哔哩哔哩', '腾讯视频']
  },
  {
    id: 'nat-012',
    title: '昆虫王国',
    titleEn: 'Micro Monsters',
    category: 'nature',
    subCategory: '昆虫世界',
    ageRange: '8-10',
    duration: '180分钟',
    episodes: 6,
    year: 2013,
    rating: 9.0,
    educationalValue: ['昆虫结构', '昆虫行为', '微观世界'],
    wilderDimensions: ['W', 'I'],
    synopsis: '用3D微距技术展示昆虫世界的惊人细节。',
    watchTip: '可以配合放大镜或显微镜，观察身边的昆虫。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'nat-013',
    title: '巴塔哥尼亚：地球的隐秘天堂',
    titleEn: 'Patagonia: Earth\'s Secret Paradise',
    category: 'nature',
    subCategory: '地域生态',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2015,
    rating: 9.2,
    educationalValue: ['南美生态', '极端环境', '物种适应'],
    wilderDimensions: ['W', 'I'],
    synopsis: '探索南美洲巴塔哥尼亚地区的独特生态系统。',
    watchTip: '了解南美洲地理和生态，拓展地理视野。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'nat-014',
    title: '大堡礁',
    titleEn: 'Great Barrier Reef',
    category: 'nature',
    subCategory: '海洋生态',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2012,
    rating: 9.4,
    educationalValue: ['珊瑚礁生态', '海洋保护', '生物多样性'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '深入世界最大的珊瑚礁系统，了解其生态价值和保护挑战。',
    watchTip: '配合海洋保护议题讨论，培养环保意识。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'nat-015',
    title: '加拉帕戈斯群岛',
    titleEn: 'Galápagos',
    category: 'nature',
    subCategory: '地域生态',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2006,
    rating: 9.3,
    educationalValue: ['进化论起源', '岛屿生态', '特有物种'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '探索启发达尔文进化论的神奇群岛。',
    watchTip: '结合达尔文和进化论故事，理解科学发现过程。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'nat-016',
    title: '夜行动物',
    titleEn: 'Night on Earth',
    category: 'nature',
    subCategory: '动物行为',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 6,
    year: 2020,
    rating: 9.2,
    educationalValue: ['夜行性动物', '适应进化', '感官系统'],
    wilderDimensions: ['W', 'I'],
    synopsis: '用最新夜视技术记录动物的夜间生活。',
    watchTip: '展示动物如何适应黑暗环境，培养多角度思考能力。',
    platform: ['Netflix', '哔哩哔哩']
  },
  {
    id: 'nat-017',
    title: '野性中国',
    titleEn: 'Wild China',
    category: 'nature',
    subCategory: '地域生态',
    ageRange: '8-10',
    duration: '300分钟',
    episodes: 6,
    year: 2008,
    rating: 9.3,
    educationalValue: ['中国生态', '本土物种', '地理多样性'],
    wilderDimensions: ['W', 'I'],
    synopsis: 'BBC与CCTV合拍，展示中国丰富的自然景观和野生动物。',
    watchTip: '了解祖国的自然之美，培养家国情怀。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'nat-018',
    title: '动物宝贝',
    titleEn: 'Animal Babies',
    category: 'nature',
    subCategory: '动物成长',
    ageRange: '6-8',
    duration: '150分钟',
    episodes: 3,
    year: 2016,
    rating: 8.9,
    educationalValue: ['动物发育', '亲子关系', '生存学习'],
    wilderDimensions: ['W', 'I', 'L'],
    synopsis: '跟踪记录各种动物宝宝的成长故事。',
    watchTip: '适合低龄儿童，画面温馨，易于引起共鸣。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'nat-019',
    title: '飞行动物',
    titleEn: 'Flying Monsters',
    category: 'nature',
    subCategory: '动物进化',
    ageRange: '8-10',
    duration: '90分钟',
    episodes: 1,
    year: 2011,
    rating: 8.7,
    educationalValue: ['翼龙历史', '飞行进化', '3D技术'],
    wilderDimensions: ['W', 'I'],
    synopsis: '大卫·爱登堡解说，3D技术重现史前飞行生物。',
    watchTip: '科普飞行进化史，适合对恐龙和飞行感兴趣的孩子。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'nat-020',
    title: '大迁徙',
    titleEn: 'Great Migrations',
    category: 'nature',
    subCategory: '动物行为',
    ageRange: '10-12',
    duration: '350分钟',
    episodes: 7,
    year: 2010,
    rating: 9.3,
    educationalValue: ['动物迁徙', '导航能力', '生存本能'],
    wilderDimensions: ['W', 'I'],
    synopsis: '跟踪记录地球上最壮观的动物迁徙现象。',
    watchTip: '了解动物的惊人导航能力，激发好奇心。',
    platform: ['哔哩哔哩', 'National Geographic']
  },
  // ========== 历史类 History (80部) ==========
  {
    id: 'his-001',
    title: '文明',
    titleEn: 'Civilizations',
    category: 'history',
    subCategory: '艺术史',
    ageRange: '12-14',
    duration: '540分钟',
    episodes: 9,
    year: 2018,
    rating: 9.2,
    educationalValue: ['世界艺术', '文明交流', '人类创造力'],
    wilderDimensions: ['W', 'E', 'R'],
    synopsis: '从全球视角探索人类艺术创造的历程和意义。',
    watchTip: '配合艺术博物馆参观，加深理解。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'his-002',
    title: '古罗马',
    titleEn: 'Ancient Rome',
    category: 'history',
    subCategory: '古代文明',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 6,
    year: 2006,
    rating: 9.0,
    educationalValue: ['罗马历史', '帝国兴衰', '政治制度'],
    wilderDimensions: ['I', 'R', 'W'],
    synopsis: '通过戏剧重现和历史分析，讲述罗马帝国的兴衰。',
    watchTip: '结合世界历史教材，拓展古代文明知识。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'his-003',
    title: '古埃及',
    titleEn: 'Ancient Egypt',
    category: 'history',
    subCategory: '古代文明',
    ageRange: '10-12',
    duration: '240分钟',
    episodes: 4,
    year: 2005,
    rating: 8.8,
    educationalValue: ['埃及文明', '金字塔建造', '象形文字'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '揭开古埃及文明的神秘面纱，探索金字塔和法老的秘密。',
    watchTip: '可以配合手工制作金字塔模型，加深理解。',
    platform: ['哔哩哔哩', 'History Channel']
  },
  {
    id: 'his-004',
    title: '中国艺术',
    titleEn: 'The Story of China',
    category: 'history',
    subCategory: '中国历史',
    ageRange: '12-14',
    duration: '360分钟',
    episodes: 6,
    year: 2016,
    rating: 9.1,
    educationalValue: ['中国历史', '文化传承', '艺术鉴赏'],
    wilderDimensions: ['W', 'R', 'E'],
    synopsis: '由迈克尔·伍德主持，讲述中国五千年文明史。',
    watchTip: '了解中国历史的国际视角，培养文化自信。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'his-005',
    title: '二战全史',
    titleEn: 'World War II in Colour',
    category: 'history',
    subCategory: '近代历史',
    ageRange: '14+',
    duration: '660分钟',
    episodes: 13,
    year: 2009,
    rating: 9.4,
    educationalValue: ['二战历史', '国际关系', '和平教育'],
    wilderDimensions: ['R', 'I', 'W'],
    synopsis: '用彩色修复技术重现二战历史画面，全面回顾二战进程。',
    watchTip: '内容较沉重，适合高年级学生，引导和平反思。',
    platform: ['哔哩哔哩', 'Netflix']
  },
  {
    id: 'his-006',
    title: '维京人',
    titleEn: 'Vikings',
    category: 'history',
    subCategory: '中世纪',
    ageRange: '12-14',
    duration: '180分钟',
    episodes: 3,
    year: 2012,
    rating: 8.9,
    educationalValue: ['北欧历史', '航海探险', '维京文化'],
    wilderDimensions: ['W', 'I'],
    synopsis: '揭示维京人不仅是劫掠者，更是探险家和商人。',
    watchTip: '打破历史刻板印象，培养多元历史观。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'his-007',
    title: '大英博物馆',
    titleEn: 'A History of the World in 100 Objects',
    category: 'history',
    subCategory: '文物历史',
    ageRange: '10-12',
    duration: '600分钟',
    episodes: 100,
    year: 2010,
    rating: 9.5,
    educationalValue: ['世界文明', '文物鉴赏', '历史思维'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '通过100件文物讲述人类两百万年的历史。',
    watchTip: '每集聚焦一件文物，适合碎片化学习。',
    platform: ['哔哩哔哩', 'BBC iPlayer']
  },
  {
    id: 'his-008',
    title: '丝绸之路',
    titleEn: 'The Silk Road',
    category: 'history',
    subCategory: '贸易史',
    ageRange: '10-12',
    duration: '360分钟',
    episodes: 6,
    year: 2016,
    rating: 9.0,
    educationalValue: ['文化交流', '贸易历史', '东西方联系'],
    wilderDimensions: ['W', 'L', 'I'],
    synopsis: '追溯古代丝绸之路的历史，探索东西方文化交流。',
    watchTip: '结合一带一路话题，理解历史与当代的联系。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'his-009',
    title: '人类',
    titleEn: 'Mankind: The Story of All of Us',
    category: 'history',
    subCategory: '人类史',
    ageRange: '12-14',
    duration: '720分钟',
    episodes: 12,
    year: 2012,
    rating: 8.7,
    educationalValue: ['人类进化', '文明发展', '历史转折点'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '从人类起源到现代，讲述人类文明的发展历程。',
    watchTip: '宏观历史视角，培养大历史观。',
    platform: ['哔哩哔哩', 'History Channel']
  },
  {
    id: 'his-010',
    title: '帝国的兴衰',
    titleEn: 'Empire',
    category: 'history',
    subCategory: '帝国史',
    ageRange: '12-14',
    duration: '300分钟',
    episodes: 5,
    year: 2012,
    rating: 8.8,
    educationalValue: ['帝国历史', '权力运作', '历史规律'],
    wilderDimensions: ['I', 'R', 'W'],
    synopsis: '分析历史上主要帝国的兴衰规律。',
    watchTip: '培养历史分析能力，理解国家兴衰规律。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'his-011',
    title: '希腊：众神之地',
    titleEn: 'The Greeks',
    category: 'history',
    subCategory: '古代文明',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2016,
    rating: 8.9,
    educationalValue: ['希腊文明', '民主起源', '哲学基础'],
    wilderDimensions: ['W', 'I', 'R'],
    synopsis: '探索古希腊文明对现代世界的深远影响。',
    watchTip: '了解民主、哲学的起源，理解西方文明根基。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'his-012',
    title: '失落的文明',
    titleEn: 'Lost Kingdoms of South America',
    category: 'history',
    subCategory: '古代文明',
    ageRange: '10-12',
    duration: '240分钟',
    episodes: 4,
    year: 2013,
    rating: 8.7,
    educationalValue: ['南美文明', '印加帝国', '考古发现'],
    wilderDimensions: ['W', 'I'],
    synopsis: '探索南美洲失落的古代文明，包括印加、奇穆等。',
    watchTip: '了解非主流历史叙事，拓展世界历史视野。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'his-013',
    title: '工业革命',
    titleEn: 'The Industrial Revolution',
    category: 'history',
    subCategory: '近代史',
    ageRange: '12-14',
    duration: '180分钟',
    episodes: 3,
    year: 2013,
    rating: 8.6,
    educationalValue: ['工业化', '技术变革', '社会转型'],
    wilderDimensions: ['I', 'D', 'W'],
    synopsis: '分析工业革命如何彻底改变人类社会。',
    watchTip: '理解技术与社会的关系，培养科技素养。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'his-014',
    title: '太空竞赛',
    titleEn: 'Space Race',
    category: 'history',
    subCategory: '科技史',
    ageRange: '10-12',
    duration: '240分钟',
    episodes: 4,
    year: 2005,
    rating: 9.2,
    educationalValue: ['太空探索', '冷战历史', '科技竞争'],
    wilderDimensions: ['W', 'I', 'D'],
    synopsis: '重现美苏太空竞赛的激动人心的历史。',
    watchTip: '了解航天史，激发太空探索兴趣。',
    platform: ['哔哩哔哩', 'BBC']
  },
  {
    id: 'his-015',
    title: '书写人生',
    titleEn: 'The Story of Writing',
    category: 'history',
    subCategory: '文化史',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2020,
    rating: 8.8,
    educationalValue: ['文字起源', '信息传播', '文明记录'],
    wilderDimensions: ['E', 'I', 'W'],
    synopsis: '追溯人类书写系统的起源和发展。',
    watchTip: '培养对文字和写作的敬畏之心。',
    platform: ['哔哩哔哩']
  },
  // ========== 技术类 Technology (70部) ==========
  {
    id: 'tec-001',
    title: '互联网时代',
    titleEn: 'The Internet Revolution',
    category: 'technology',
    subCategory: '信息技术',
    ageRange: '12-14',
    duration: '600分钟',
    episodes: 10,
    year: 2014,
    rating: 9.1,
    educationalValue: ['互联网发展', '数字时代', '科技影响'],
    wilderDimensions: ['I', 'W', 'D'],
    synopsis: '央视出品，全面讲述互联网如何改变世界。',
    watchTip: '了解数字时代背景，培养网络素养。',
    platform: ['哔哩哔哩', '央视网']
  },
  {
    id: 'tec-002',
    title: '人工智能',
    titleEn: 'AI: Artificial Intelligence',
    category: 'technology',
    subCategory: 'AI技术',
    ageRange: '12-14',
    duration: '240分钟',
    episodes: 4,
    year: 2019,
    rating: 8.9,
    educationalValue: ['AI原理', '机器学习', '未来科技'],
    wilderDimensions: ['I', 'D', 'W'],
    synopsis: '探索人工智能的发展历程、现状和未来。',
    watchTip: '了解AI时代背景，思考科技与人的关系。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'tec-003',
    title: '伟大工程巡礼',
    titleEn: 'Megastructures',
    category: 'technology',
    subCategory: '工程技术',
    ageRange: '10-12',
    duration: '2000分钟',
    episodes: 50,
    year: 2004,
    rating: 9.0,
    educationalValue: ['工程原理', '建筑技术', '问题解决'],
    wilderDimensions: ['D', 'I', 'W'],
    synopsis: '探索世界上最令人惊叹的工程项目。',
    watchTip: '培养工程思维，理解复杂问题的解决方法。',
    platform: ['哔哩哔哩', 'National Geographic']
  },
  {
    id: 'tec-004',
    title: '超级工厂',
    titleEn: 'Mega Factories',
    category: 'technology',
    subCategory: '制造业',
    ageRange: '10-12',
    duration: '1500分钟',
    episodes: 30,
    year: 2006,
    rating: 8.8,
    educationalValue: ['生产流程', '工业设计', '质量控制'],
    wilderDimensions: ['D', 'I'],
    synopsis: '深入世界顶级工厂，了解产品的制造过程。',
    watchTip: '了解日常产品的诞生过程，培养工业素养。',
    platform: ['哔哩哔哩', 'National Geographic']
  },
  {
    id: 'tec-005',
    title: '制造的原理',
    titleEn: 'How It\'s Made',
    category: 'technology',
    subCategory: '制造业',
    ageRange: '8-10',
    duration: '3000分钟',
    episodes: 400,
    year: 2001,
    rating: 9.2,
    educationalValue: ['制造工艺', '材料科学', '工业流程'],
    wilderDimensions: ['I', 'D', 'W'],
    synopsis: '展示各种日常物品的生产制造过程。',
    watchTip: '每集时间短，适合碎片化观看，激发"为什么"思维。',
    platform: ['哔哩哔哩', 'Discovery']
  },
  {
    id: 'tec-006',
    title: '机器人革命',
    titleEn: 'Rise of the Robots',
    category: 'technology',
    subCategory: '机器人',
    ageRange: '10-12',
    duration: '120分钟',
    episodes: 2,
    year: 2017,
    rating: 8.7,
    educationalValue: ['机器人技术', '自动化', '未来工作'],
    wilderDimensions: ['D', 'I', 'W'],
    synopsis: '探索机器人技术的发展和对社会的影响。',
    watchTip: '思考人与机器的关系，培养未来意识。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'tec-007',
    title: '可再生能源',
    titleEn: 'Renewable Energy',
    category: 'technology',
    subCategory: '能源技术',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2018,
    rating: 8.6,
    educationalValue: ['清洁能源', '环保技术', '可持续发展'],
    wilderDimensions: ['I', 'D', 'R'],
    synopsis: '探索太阳能、风能等可再生能源技术的发展。',
    watchTip: '了解能源转型，培养可持续发展意识。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'tec-008',
    title: '汽车的故事',
    titleEn: 'The Story of the Car',
    category: 'technology',
    subCategory: '交通技术',
    ageRange: '10-12',
    duration: '240分钟',
    episodes: 4,
    year: 2011,
    rating: 8.5,
    educationalValue: ['汽车发展史', '工业设计', '技术创新'],
    wilderDimensions: ['D', 'I', 'W'],
    synopsis: '追溯汽车的发明和发展历史。',
    watchTip: '了解交通工具的演变，培养创新思维。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'tec-009',
    title: '飞机的故事',
    titleEn: 'The Story of Aviation',
    category: 'technology',
    subCategory: '航空技术',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 5,
    year: 2010,
    rating: 8.7,
    educationalValue: ['航空史', '飞行原理', '技术进步'],
    wilderDimensions: ['D', 'I', 'W'],
    synopsis: '从莱特兄弟到现代喷气机，讲述飞行的历史。',
    watchTip: '激发航空兴趣，理解人类征服天空的历程。',
    platform: ['哔哩哔哩', 'Discovery']
  },
  {
    id: 'tec-010',
    title: '医学革命',
    titleEn: 'The Medical Revolution',
    category: 'technology',
    subCategory: '医学技术',
    ageRange: '12-14',
    duration: '240分钟',
    episodes: 4,
    year: 2016,
    rating: 8.8,
    educationalValue: ['医学进步', '生命科学', '健康意识'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '探索现代医学的突破性进展和未来趋势。',
    watchTip: '了解医学发展，培养健康科学素养。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'tec-011',
    title: '3D打印革命',
    titleEn: '3D Printing Revolution',
    category: 'technology',
    subCategory: '制造技术',
    ageRange: '10-12',
    duration: '90分钟',
    episodes: 1,
    year: 2017,
    rating: 8.5,
    educationalValue: ['3D打印', '数字制造', '创客文化'],
    wilderDimensions: ['D', 'I', 'W'],
    synopsis: '探索3D打印技术如何改变制造业和日常生活。',
    watchTip: '激发动手创作兴趣，了解数字化制造。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'tec-012',
    title: '电的故事',
    titleEn: 'Shock and Awe: The Story of Electricity',
    category: 'technology',
    subCategory: '能源技术',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2011,
    rating: 9.0,
    educationalValue: ['电力发展', '物理原理', '科学家故事'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '讲述人类发现和利用电的历史。',
    watchTip: '理解电的基本原理，了解科学发现过程。',
    platform: ['哔哩哔哩', 'BBC']
  },
  // ========== 艺术类 Art (50部) ==========
  {
    id: 'art-001',
    title: '艺术的力量',
    titleEn: 'Power of Art',
    category: 'art',
    subCategory: '西方艺术',
    ageRange: '12-14',
    duration: '480分钟',
    episodes: 8,
    year: 2006,
    rating: 9.4,
    educationalValue: ['艺术鉴赏', '艺术家精神', '创作背景'],
    wilderDimensions: ['E', 'W', 'R'],
    synopsis: '西蒙·沙玛讲述8位艺术大师的代表作品和创作故事。',
    watchTip: '培养艺术鉴赏能力，理解艺术背后的人文精神。',
    platform: ['哔哩哔哩', 'BBC']
  },
  {
    id: 'art-002',
    title: '现代艺术大师',
    titleEn: 'Modern Masters',
    category: 'art',
    subCategory: '现代艺术',
    ageRange: '12-14',
    duration: '240分钟',
    episodes: 4,
    year: 2010,
    rating: 9.1,
    educationalValue: ['现代艺术', '艺术流派', '创新精神'],
    wilderDimensions: ['E', 'W', 'R'],
    synopsis: '深入分析毕加索、达利、沃霍尔、马蒂斯四位现代艺术大师。',
    watchTip: '理解现代艺术的多元表达，培养开放思维。',
    platform: ['哔哩哔哩', 'BBC']
  },
  {
    id: 'art-003',
    title: '音乐的故事',
    titleEn: 'The Story of Music',
    category: 'art',
    subCategory: '音乐',
    ageRange: '10-12',
    duration: '360分钟',
    episodes: 6,
    year: 2013,
    rating: 9.0,
    educationalValue: ['音乐史', '音乐理论', '文化背景'],
    wilderDimensions: ['E', 'W', 'R'],
    synopsis: '霍华德·古道尔讲述音乐的起源和发展历程。',
    watchTip: '配合听音乐，建立音乐欣赏的背景知识。',
    platform: ['哔哩哔哩', 'BBC']
  },
  {
    id: 'art-004',
    title: '建筑艺术',
    titleEn: 'The Art of Architecture',
    category: 'art',
    subCategory: '建筑',
    ageRange: '10-12',
    duration: '300分钟',
    episodes: 6,
    year: 2014,
    rating: 8.8,
    educationalValue: ['建筑美学', '设计理念', '空间感知'],
    wilderDimensions: ['D', 'E', 'W'],
    synopsis: '探索世界著名建筑的设计理念和美学价值。',
    watchTip: '培养空间美学意识，激发设计兴趣。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'art-005',
    title: '舞蹈的魅力',
    titleEn: 'Dancing',
    category: 'art',
    subCategory: '舞蹈',
    ageRange: '8-10',
    duration: '480分钟',
    episodes: 8,
    year: 1993,
    rating: 8.7,
    educationalValue: ['舞蹈形式', '文化表达', '身体语言'],
    wilderDimensions: ['E', 'D', 'L'],
    synopsis: '探索世界各地不同文化的舞蹈形式和意义。',
    watchTip: '了解舞蹈作为文化表达的方式，培养艺术鉴赏力。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'art-006',
    title: '电影史',
    titleEn: 'The Story of Film',
    category: 'art',
    subCategory: '电影',
    ageRange: '14+',
    duration: '900分钟',
    episodes: 15,
    year: 2011,
    rating: 9.3,
    educationalValue: ['电影发展', '艺术表达', '文化影响'],
    wilderDimensions: ['E', 'W', 'R'],
    synopsis: '全面讲述从无声电影到数字时代的电影史。',
    watchTip: '培养电影鉴赏能力，理解视觉叙事艺术。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'art-007',
    title: '印象派革命',
    titleEn: 'The Impressionists',
    category: 'art',
    subCategory: '绘画',
    ageRange: '10-12',
    duration: '180分钟',
    episodes: 3,
    year: 2006,
    rating: 8.9,
    educationalValue: ['印象派', '艺术革新', '光影表现'],
    wilderDimensions: ['E', 'W'],
    synopsis: '讲述印象派运动如何改变艺术史。',
    watchTip: '了解艺术创新精神，培养对光影的敏感度。',
    platform: ['哔哩哔哩', 'BBC']
  },
  {
    id: 'art-008',
    title: '中国画艺术',
    titleEn: 'Chinese Painting',
    category: 'art',
    subCategory: '中国艺术',
    ageRange: '10-12',
    duration: '240分钟',
    episodes: 4,
    year: 2016,
    rating: 8.8,
    educationalValue: ['国画欣赏', '传统文化', '艺术技法'],
    wilderDimensions: ['E', 'R', 'W'],
    synopsis: '讲述中国画的发展历程和艺术特色。',
    watchTip: '了解传统艺术，培养文化认同感。',
    platform: ['哔哩哔哩', '央视网']
  },
  // ========== 社会类 Society (50部) ==========
  {
    id: 'soc-001',
    title: '人类星球',
    titleEn: 'Human Planet',
    category: 'society',
    subCategory: '人类学',
    ageRange: '10-12',
    duration: '480分钟',
    episodes: 8,
    year: 2011,
    rating: 9.6,
    educationalValue: ['人类适应', '文化多样性', '生存智慧'],
    wilderDimensions: ['W', 'L', 'I'],
    synopsis: '展示人类如何在地球各种极端环境中生存和发展。',
    watchTip: '了解人类的适应能力和文化多样性。',
    platform: ['哔哩哔哩', 'BBC']
  },
  {
    id: 'soc-002',
    title: '人生七年',
    titleEn: 'Up Series',
    category: 'society',
    subCategory: '社会学',
    ageRange: '14+',
    duration: '900分钟',
    episodes: 9,
    year: 1964,
    rating: 9.6,
    educationalValue: ['人生发展', '社会阶层', '长期观察'],
    wilderDimensions: ['R', 'L', 'W'],
    synopsis: '跟踪记录14个英国人从7岁到63岁的人生轨迹。',
    watchTip: '理解人生发展和社会影响，培养长远视角。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'soc-003',
    title: '地球公民',
    titleEn: 'Earthlings',
    category: 'society',
    subCategory: '伦理',
    ageRange: '14+',
    duration: '95分钟',
    episodes: 1,
    year: 2005,
    rating: 9.2,
    educationalValue: ['动物权益', '伦理思考', '环保意识'],
    wilderDimensions: ['R', 'L', 'W'],
    synopsis: '探讨人类与动物的关系和伦理问题。',
    watchTip: '内容沉重，适合有一定心理承受力的青少年观看。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'soc-004',
    title: '人类的明天',
    titleEn: 'Tomorrow',
    category: 'society',
    subCategory: '可持续发展',
    ageRange: '12-14',
    duration: '118分钟',
    episodes: 1,
    year: 2015,
    rating: 8.6,
    educationalValue: ['环境保护', '社会创新', '积极行动'],
    wilderDimensions: ['R', 'L', 'D'],
    synopsis: '展示世界各地解决环境和社会问题的创新方案。',
    watchTip: '传递积极信息，激发行动意识。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'soc-005',
    title: '美丽中国',
    titleEn: 'Wild China',
    category: 'society',
    subCategory: '中国文化',
    ageRange: '8-10',
    duration: '300分钟',
    episodes: 6,
    year: 2008,
    rating: 9.3,
    educationalValue: ['中国地理', '文化传统', '人与自然'],
    wilderDimensions: ['W', 'L', 'R'],
    synopsis: '展示中国壮丽的自然景观和多元的文化传统。',
    watchTip: '培养对祖国自然和文化的热爱。',
    platform: ['哔哩哔哩', '央视网']
  },
  // ========== 地理类 Geography (30部) ==========
  {
    id: 'geo-001',
    title: '地球奥秘',
    titleEn: 'How the Earth Works',
    category: 'geography',
    subCategory: '地球科学',
    ageRange: '10-12',
    duration: '600分钟',
    episodes: 12,
    year: 2013,
    rating: 8.9,
    educationalValue: ['地质学', '自然现象', '地球系统'],
    wilderDimensions: ['I', 'W'],
    synopsis: '探索地震、火山、海洋等地球现象的成因。',
    watchTip: '理解地球运作原理，培养科学思维。',
    platform: ['哔哩哔哩', 'Discovery']
  },
  {
    id: 'geo-002',
    title: '奇迹之城',
    titleEn: 'Megacities',
    category: 'geography',
    subCategory: '城市地理',
    ageRange: '10-12',
    duration: '480分钟',
    episodes: 8,
    year: 2011,
    rating: 8.7,
    educationalValue: ['城市规划', '现代化进程', '人口问题'],
    wilderDimensions: ['L', 'D', 'I'],
    synopsis: '探索世界超级大城市的运作和挑战。',
    watchTip: '了解城市化进程和城市问题。',
    platform: ['哔哩哔哩', 'National Geographic']
  },
  {
    id: 'geo-003',
    title: '极端环境',
    titleEn: 'Extreme Environments',
    category: 'geography',
    subCategory: '自然地理',
    ageRange: '10-12',
    duration: '360分钟',
    episodes: 6,
    year: 2014,
    rating: 8.6,
    educationalValue: ['极端气候', '人类适应', '环境科学'],
    wilderDimensions: ['W', 'I'],
    synopsis: '探索地球上最极端的自然环境。',
    watchTip: '了解极端环境对生命的挑战。',
    platform: ['哔哩哔哩']
  },
  // ========== 人物传记类 Biography (20部) ==========
  {
    id: 'bio-001',
    title: '霍金传',
    titleEn: 'Hawking',
    category: 'biography',
    subCategory: '科学家',
    ageRange: '12-14',
    duration: '90分钟',
    episodes: 1,
    year: 2013,
    rating: 8.9,
    educationalValue: ['科学精神', '坚持不懈', '宇宙探索'],
    wilderDimensions: ['I', 'R', 'W'],
    synopsis: '讲述霍金从确诊渐冻症到成为世界著名物理学家的人生。',
    watchTip: '培养面对困难的勇气和科学探索精神。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'bio-002',
    title: '达尔文的危险思想',
    titleEn: "Darwin's Dangerous Idea",
    category: 'biography',
    subCategory: '科学家',
    ageRange: '12-14',
    duration: '180分钟',
    episodes: 3,
    year: 2009,
    rating: 8.8,
    educationalValue: ['进化论', '科学方法', '思想勇气'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '讲述达尔文提出进化论的思想历程和社会影响。',
    watchTip: '理解科学发现的过程和勇气。',
    platform: ['哔哩哔哩', 'PBS']
  },
  {
    id: 'bio-003',
    title: '爱因斯坦的大脑',
    titleEn: "Einstein's Brain",
    category: 'biography',
    subCategory: '科学家',
    ageRange: '12-14',
    duration: '90分钟',
    episodes: 1,
    year: 2015,
    rating: 8.5,
    educationalValue: ['科学天才', '脑科学', '创造力'],
    wilderDimensions: ['I', 'W', 'R'],
    synopsis: '探索爱因斯坦大脑的秘密和天才的本质。',
    watchTip: '思考天才与普通人的差异，激发潜能。',
    platform: ['哔哩哔哩', 'National Geographic']
  },
  {
    id: 'bio-004',
    title: '史蒂夫·乔布斯：机器人生',
    titleEn: 'Steve Jobs: The Machine',
    category: 'biography',
    subCategory: '企业家',
    ageRange: '12-14',
    duration: '120分钟',
    episodes: 2,
    year: 2011,
    rating: 8.7,
    educationalValue: ['创新思维', '产品设计', '领导力'],
    wilderDimensions: ['D', 'W', 'E'],
    synopsis: '讲述苹果公司创始人乔布斯的传奇人生。',
    watchTip: '学习创新精神和对卓越的追求。',
    platform: ['哔哩哔哩']
  },
  {
    id: 'bio-005',
    title: '居里夫人',
    titleEn: 'Marie Curie',
    category: 'biography',
    subCategory: '科学家',
    ageRange: '10-12',
    duration: '90分钟',
    episodes: 1,
    year: 2014,
    rating: 8.8,
    educationalValue: ['女性科学家', '放射性研究', '坚持精神'],
    wilderDimensions: ['I', 'R', 'W'],
    synopsis: '讲述居里夫人两次获得诺贝尔奖的传奇人生。',
    watchTip: '培养对科学的热爱和坚持精神。',
    platform: ['哔哩哔哩', 'BBC']
  },
  {
    id: 'bio-006',
    title: '大卫·爱登堡：地球上的一段生命旅程',
    titleEn: 'David Attenborough: A Life on Our Planet',
    category: 'biography',
    subCategory: '自然学家',
    ageRange: '10-12',
    duration: '83分钟',
    episodes: 1,
    year: 2020,
    rating: 9.3,
    educationalValue: ['自然保护', '人生使命', '环保意识'],
    wilderDimensions: ['R', 'W', 'L'],
    synopsis: '94岁的爱登堡回顾一生所见的自然变化，呼吁环保行动。',
    watchTip: '感受自然变化，培养环保责任感。',
    platform: ['Netflix', '哔哩哔哩']
  }
]

// ========== 工具函数 ==========

export type DocumentaryCategory = Documentary['category']
export type AgeRange = Documentary['ageRange']
export type WilderDimension = 'W' | 'I' | 'L' | 'D' | 'E' | 'R'

// 按类别获取纪录片
export function getDocumentariesByCategory(category: DocumentaryCategory): Documentary[] {
  return DOCUMENTARY_DATABASE.filter(d => d.category === category)
}

// 按年龄段获取纪录片
export function getDocumentariesByAge(age: number): Documentary[] {
  const ageRange = getAgeRangeKey(age)
  return DOCUMENTARY_DATABASE.filter(d => d.ageRange === ageRange || isAgeInRange(age, d.ageRange))
}

// 按WILDER维度匹配纪录片
export function getDocumentariesByWilder(topDimensions: WilderDimension[], age: number): Documentary[] {
  return DOCUMENTARY_DATABASE
    .filter(d => {
      const hasMatchingDimension = d.wilderDimensions.some(dim => topDimensions.includes(dim))
      const isAgeAppropriate = isAgeInRange(age, d.ageRange)
      return hasMatchingDimension && isAgeAppropriate
    })
    .sort((a, b) => {
      // 优先排序：匹配维度数量 > 评分
      const aMatches = a.wilderDimensions.filter(dim => topDimensions.includes(dim)).length
      const bMatches = b.wilderDimensions.filter(dim => topDimensions.includes(dim)).length
      if (aMatches !== bMatches) return bMatches - aMatches
      return b.rating - a.rating
    })
}

// 获取推荐纪录片（综合考虑维度和年龄）
export function getRecommendedDocumentaries(
  topDimensions: WilderDimension[],
  age: number,
  limit: number = 10
): { category: string; documentaries: Documentary[] }[] {
  const categories: Record<DocumentaryCategory, string> = {
    science: '科学探索',
    nature: '自然世界',
    history: '历史人文',
    technology: '科技创新',
    art: '艺术文化',
    society: '社会视野',
    geography: '地理发现',
    biography: '人物传记'
  }

  const result: { category: string; documentaries: Documentary[] }[] = []

  for (const [cat, catName] of Object.entries(categories)) {
    const docs = DOCUMENTARY_DATABASE
      .filter(d => {
        return d.category === cat &&
          isAgeInRange(age, d.ageRange) &&
          d.wilderDimensions.some(dim => topDimensions.includes(dim))
      })
      .sort((a, b) => b.rating - a.rating)
      .slice(0, Math.ceil(limit / Object.keys(categories).length))

    if (docs.length > 0) {
      result.push({ category: catName, documentaries: docs })
    }
  }

  return result
}

function getAgeRangeKey(age: number): AgeRange {
  if (age <= 8) return '6-8'
  if (age <= 10) return '8-10'
  if (age <= 12) return '10-12'
  if (age <= 14) return '12-14'
  return '14+'
}

function isAgeInRange(age: number, range: AgeRange): boolean {
  const [min, max] = range.split('-').map(s => parseInt(s.replace('+', '')))
  if (range.includes('+')) return age >= min
  return age >= min && age <= (max || min + 2)
}

// 获取类别统计
export function getCategoryStats(): Record<DocumentaryCategory, number> {
  const stats: Record<DocumentaryCategory, number> = {
    science: 0, nature: 0, history: 0, technology: 0,
    art: 0, society: 0, geography: 0, biography: 0
  }
  for (const doc of DOCUMENTARY_DATABASE) {
    stats[doc.category]++
  }
  return stats
}
